package com.pkuvr.login_server.dao;

import com.pkuvr.login_server.domain.PlayerLoginLogs;
import com.pkuvr.login_server.domain.PlayerLoginLogsExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository("PlayerLoginLogsMapper")
public interface PlayerLoginLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Player_Login_Logs
     *
     * @mbggenerated Wed Aug 22 15:45:17 CST 2012
     */
    int countByExample(PlayerLoginLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Player_Login_Logs
     *
     * @mbggenerated Wed Aug 22 15:45:17 CST 2012
     */
    int deleteByExample(PlayerLoginLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Player_Login_Logs
     *
     * @mbggenerated Wed Aug 22 15:45:17 CST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Player_Login_Logs
     *
     * @mbggenerated Wed Aug 22 15:45:17 CST 2012
     */
    int insert(PlayerLoginLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Player_Login_Logs
     *
     * @mbggenerated Wed Aug 22 15:45:17 CST 2012
     */
    int insertSelective(PlayerLoginLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Player_Login_Logs
     *
     * @mbggenerated Wed Aug 22 15:45:17 CST 2012
     */
    List<PlayerLoginLogs> selectByExample(PlayerLoginLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Player_Login_Logs
     *
     * @mbggenerated Wed Aug 22 15:45:17 CST 2012
     */
    PlayerLoginLogs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Player_Login_Logs
     *
     * @mbggenerated Wed Aug 22 15:45:17 CST 2012
     */
    int updateByExampleSelective(@Param("record") PlayerLoginLogs record, @Param("example") PlayerLoginLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Player_Login_Logs
     *
     * @mbggenerated Wed Aug 22 15:45:17 CST 2012
     */
    int updateByExample(@Param("record") PlayerLoginLogs record, @Param("example") PlayerLoginLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Player_Login_Logs
     *
     * @mbggenerated Wed Aug 22 15:45:17 CST 2012
     */
    int updateByPrimaryKeySelective(PlayerLoginLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Player_Login_Logs
     *
     * @mbggenerated Wed Aug 22 15:45:17 CST 2012
     */
    int updateByPrimaryKey(PlayerLoginLogs record);
}