package com.pkuvr.manage_server.domain;

import java.util.Date;

public class ExchangeCodeCreate {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Exchange_Code_Create.ID
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Exchange_Code_Create.Channel
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    private String channel;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Exchange_Code_Create.Description
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    private String description;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Exchange_Code_Create.Game_ID
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    private Integer gameId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Exchange_Code_Create.Mail_ID
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    private Integer mailId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Exchange_Code_Create.Download_Url
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    private String downloadUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Exchange_Code_Create.Add_Time
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Exchange_Code_Create.ID
     *
     * @return the value of Exchange_Code_Create.ID
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Exchange_Code_Create.ID
     *
     * @param id the value for Exchange_Code_Create.ID
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Exchange_Code_Create.Channel
     *
     * @return the value of Exchange_Code_Create.Channel
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Exchange_Code_Create.Channel
     *
     * @param channel the value for Exchange_Code_Create.Channel
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Exchange_Code_Create.Description
     *
     * @return the value of Exchange_Code_Create.Description
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Exchange_Code_Create.Description
     *
     * @param description the value for Exchange_Code_Create.Description
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Exchange_Code_Create.Game_ID
     *
     * @return the value of Exchange_Code_Create.Game_ID
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Exchange_Code_Create.Game_ID
     *
     * @param gameId the value for Exchange_Code_Create.Game_ID
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Exchange_Code_Create.Mail_ID
     *
     * @return the value of Exchange_Code_Create.Mail_ID
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    public Integer getMailId() {
        return mailId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Exchange_Code_Create.Mail_ID
     *
     * @param mailId the value for Exchange_Code_Create.Mail_ID
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    public void setMailId(Integer mailId) {
        this.mailId = mailId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Exchange_Code_Create.Download_Url
     *
     * @return the value of Exchange_Code_Create.Download_Url
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Exchange_Code_Create.Download_Url
     *
     * @param downloadUrl the value for Exchange_Code_Create.Download_Url
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Exchange_Code_Create.Add_Time
     *
     * @return the value of Exchange_Code_Create.Add_Time
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Exchange_Code_Create.Add_Time
     *
     * @param addTime the value for Exchange_Code_Create.Add_Time
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}