package com.pkuvr.manage_server.domain;

public class SystemMailToServerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column System_Mail_To_Server.Mail_ID
     *
     * @mbggenerated Thu May 15 16:52:10 CST 2014
     */
    private Integer mailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column System_Mail_To_Server.Server_ID
     *
     * @mbggenerated Thu May 15 16:52:10 CST 2014
     */
    private String serverId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column System_Mail_To_Server.Mail_ID
     *
     * @return the value of System_Mail_To_Server.Mail_ID
     * @mbggenerated Thu May 15 16:52:10 CST 2014
     */
    public Integer getMailId() {
        return mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column System_Mail_To_Server.Mail_ID
     *
     * @param mailId the value for System_Mail_To_Server.Mail_ID
     * @mbggenerated Thu May 15 16:52:10 CST 2014
     */
    public void setMailId(Integer mailId) {
        this.mailId = mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column System_Mail_To_Server.Server_ID
     *
     * @return the value of System_Mail_To_Server.Server_ID
     * @mbggenerated Thu May 15 16:52:10 CST 2014
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column System_Mail_To_Server.Server_ID
     *
     * @param serverId the value for System_Mail_To_Server.Server_ID
     * @mbggenerated Thu May 15 16:52:10 CST 2014
     */
    public void setServerId(String serverId) {
        this.serverId = serverId;
    }
}