// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mine_Harvest_Query_Res.proto

package com.pkuvr.game_server.proto.serverproto;

public final class Mine_Harvest_Query_Response {
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Mine_Harvest_Query_Res_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Mine_Harvest_Query_Res_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\034Mine_Harvest_Query_Res.proto\032\026BI_Mine_" +
                        "Resource.proto\"S\n\026Mine_Harvest_Query_Res" +
                        "\022\021\n\terrorCode\030\001 \002(\005\022&\n\nharvestRes\030\002 \003(\0132" +
                        "\022.Mine_Resource_MesBD\n%com.gfan.gameserv" +
                        "er.proto.serverprotoB\033Mine_Harvest_Query" +
                        "_Response"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_Mine_Harvest_Query_Res_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_Mine_Harvest_Query_Res_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_Mine_Harvest_Query_Res_descriptor,
                                new String[]{"ErrorCode", "HarvestRes",},
                                com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res.class,
                                com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.pkuvr.game_server.proto.commons.BI_Mine_Resource.getDescriptor(),
                        }, assigner);
    }

    private Mine_Harvest_Query_Response() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface Mine_Harvest_Query_ResOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required int32 errorCode = 1;
        boolean hasErrorCode();

        int getErrorCode();

        // repeated .Mine_Resource_Mes harvestRes = 2;
        java.util.List<com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes>
        getHarvestResList();

        com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes getHarvestRes(int index);

        int getHarvestResCount();

        java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_MesOrBuilder>
        getHarvestResOrBuilderList();

        com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_MesOrBuilder getHarvestResOrBuilder(
                int index);
    }

    public static final class Mine_Harvest_Query_Res extends
            com.google.protobuf.GeneratedMessage
            implements Mine_Harvest_Query_ResOrBuilder {
        // required int32 errorCode = 1;
        public static final int ERRORCODE_FIELD_NUMBER = 1;
        // repeated .Mine_Resource_Mes harvestRes = 2;
        public static final int HARVESTRES_FIELD_NUMBER = 2;
        private static final Mine_Harvest_Query_Res defaultInstance;
        private static final long serialVersionUID = 0L;

        static {
            defaultInstance = new Mine_Harvest_Query_Res(true);
            defaultInstance.initFields();
        }

        private int bitField0_;
        private int errorCode_;
        private java.util.List<com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes> harvestRes_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Mine_Harvest_Query_Res.newBuilder() to construct.
        private Mine_Harvest_Query_Res(Builder builder) {
            super(builder);
        }

        private Mine_Harvest_Query_Res(boolean noInit) {
        }

        public static Mine_Harvest_Query_Res getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.internal_static_Mine_Harvest_Query_Res_descriptor;
        }

        public static com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Mine_Harvest_Query_Res getDefaultInstanceForType() {
            return defaultInstance;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.internal_static_Mine_Harvest_Query_Res_fieldAccessorTable;
        }

        public boolean hasErrorCode() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getErrorCode() {
            return errorCode_;
        }

        public java.util.List<com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes> getHarvestResList() {
            return harvestRes_;
        }

        public java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_MesOrBuilder>
        getHarvestResOrBuilderList() {
            return harvestRes_;
        }

        public int getHarvestResCount() {
            return harvestRes_.size();
        }

        public com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes getHarvestRes(int index) {
            return harvestRes_.get(index);
        }

        public com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_MesOrBuilder getHarvestResOrBuilder(
                int index) {
            return harvestRes_.get(index);
        }

        private void initFields() {
            errorCode_ = 0;
            harvestRes_ = java.util.Collections.emptyList();
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasErrorCode()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, errorCode_);
            }
            for (int i = 0; i < harvestRes_.size(); i++) {
                output.writeMessage(2, harvestRes_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, errorCode_);
            }
            for (int i = 0; i < harvestRes_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, harvestRes_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_ResOrBuilder {
            private int bitField0_;
            // required int32 errorCode = 1;
            private int errorCode_;
            // repeated .Mine_Resource_Mes harvestRes = 2;
            private java.util.List<com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes> harvestRes_ =
                    java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilder<
                    com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes, com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.Builder, com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_MesOrBuilder> harvestResBuilder_;

            // Construct using com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.internal_static_Mine_Harvest_Query_Res_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.internal_static_Mine_Harvest_Query_Res_fieldAccessorTable;
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getHarvestResFieldBuilder();
                }
            }

            public Builder clear() {
                super.clear();
                errorCode_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                if (harvestResBuilder_ == null) {
                    harvestRes_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                } else {
                    harvestResBuilder_.clear();
                }
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res.getDescriptor();
            }

            public com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res getDefaultInstanceForType() {
                return com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res.getDefaultInstance();
            }

            public com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res build() {
                com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res buildPartial() {
                com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res result = new com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.errorCode_ = errorCode_;
                if (harvestResBuilder_ == null) {
                    if (((bitField0_ & 0x00000002) == 0x00000002)) {
                        harvestRes_ = java.util.Collections.unmodifiableList(harvestRes_);
                        bitField0_ = (bitField0_ & ~0x00000002);
                    }
                    result.harvestRes_ = harvestRes_;
                } else {
                    result.harvestRes_ = harvestResBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res) {
                    return mergeFrom((com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res other) {
                if (other == com.pkuvr.game_server.proto.serverproto.Mine_Harvest_Query_Response.Mine_Harvest_Query_Res.getDefaultInstance())
                    return this;
                if (other.hasErrorCode()) {
                    setErrorCode(other.getErrorCode());
                }
                if (harvestResBuilder_ == null) {
                    if (!other.harvestRes_.isEmpty()) {
                        if (harvestRes_.isEmpty()) {
                            harvestRes_ = other.harvestRes_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                        } else {
                            ensureHarvestResIsMutable();
                            harvestRes_.addAll(other.harvestRes_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.harvestRes_.isEmpty()) {
                        if (harvestResBuilder_.isEmpty()) {
                            harvestResBuilder_.dispose();
                            harvestResBuilder_ = null;
                            harvestRes_ = other.harvestRes_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                            harvestResBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getHarvestResFieldBuilder() : null;
                        } else {
                            harvestResBuilder_.addAllMessages(other.harvestRes_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasErrorCode()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            errorCode_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.Builder subBuilder = com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.newBuilder();
                            input.readMessage(subBuilder, extensionRegistry);
                            addHarvestRes(subBuilder.buildPartial());
                            break;
                        }
                    }
                }
            }

            public boolean hasErrorCode() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getErrorCode() {
                return errorCode_;
            }

            public Builder setErrorCode(int value) {
                bitField0_ |= 0x00000001;
                errorCode_ = value;
                onChanged();
                return this;
            }

            public Builder clearErrorCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                errorCode_ = 0;
                onChanged();
                return this;
            }

            private void ensureHarvestResIsMutable() {
                if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                    harvestRes_ = new java.util.ArrayList<com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes>(harvestRes_);
                    bitField0_ |= 0x00000002;
                }
            }

            public java.util.List<com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes> getHarvestResList() {
                if (harvestResBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(harvestRes_);
                } else {
                    return harvestResBuilder_.getMessageList();
                }
            }

            public int getHarvestResCount() {
                if (harvestResBuilder_ == null) {
                    return harvestRes_.size();
                } else {
                    return harvestResBuilder_.getCount();
                }
            }

            public com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes getHarvestRes(int index) {
                if (harvestResBuilder_ == null) {
                    return harvestRes_.get(index);
                } else {
                    return harvestResBuilder_.getMessage(index);
                }
            }

            public Builder setHarvestRes(
                    int index, com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes value) {
                if (harvestResBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureHarvestResIsMutable();
                    harvestRes_.set(index, value);
                    onChanged();
                } else {
                    harvestResBuilder_.setMessage(index, value);
                }
                return this;
            }

            public Builder setHarvestRes(
                    int index, com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.Builder builderForValue) {
                if (harvestResBuilder_ == null) {
                    ensureHarvestResIsMutable();
                    harvestRes_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    harvestResBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addHarvestRes(com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes value) {
                if (harvestResBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureHarvestResIsMutable();
                    harvestRes_.add(value);
                    onChanged();
                } else {
                    harvestResBuilder_.addMessage(value);
                }
                return this;
            }

            public Builder addHarvestRes(
                    int index, com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes value) {
                if (harvestResBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureHarvestResIsMutable();
                    harvestRes_.add(index, value);
                    onChanged();
                } else {
                    harvestResBuilder_.addMessage(index, value);
                }
                return this;
            }

            public Builder addHarvestRes(
                    com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.Builder builderForValue) {
                if (harvestResBuilder_ == null) {
                    ensureHarvestResIsMutable();
                    harvestRes_.add(builderForValue.build());
                    onChanged();
                } else {
                    harvestResBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            public Builder addHarvestRes(
                    int index, com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.Builder builderForValue) {
                if (harvestResBuilder_ == null) {
                    ensureHarvestResIsMutable();
                    harvestRes_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    harvestResBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addAllHarvestRes(
                    Iterable<? extends com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes> values) {
                if (harvestResBuilder_ == null) {
                    ensureHarvestResIsMutable();
                    super.addAll(values, harvestRes_);
                    onChanged();
                } else {
                    harvestResBuilder_.addAllMessages(values);
                }
                return this;
            }

            public Builder clearHarvestRes() {
                if (harvestResBuilder_ == null) {
                    harvestRes_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                    onChanged();
                } else {
                    harvestResBuilder_.clear();
                }
                return this;
            }

            public Builder removeHarvestRes(int index) {
                if (harvestResBuilder_ == null) {
                    ensureHarvestResIsMutable();
                    harvestRes_.remove(index);
                    onChanged();
                } else {
                    harvestResBuilder_.remove(index);
                }
                return this;
            }

            public com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.Builder getHarvestResBuilder(
                    int index) {
                return getHarvestResFieldBuilder().getBuilder(index);
            }

            public com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_MesOrBuilder getHarvestResOrBuilder(
                    int index) {
                if (harvestResBuilder_ == null) {
                    return harvestRes_.get(index);
                } else {
                    return harvestResBuilder_.getMessageOrBuilder(index);
                }
            }

            public java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_MesOrBuilder>
            getHarvestResOrBuilderList() {
                if (harvestResBuilder_ != null) {
                    return harvestResBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(harvestRes_);
                }
            }

            public com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.Builder addHarvestResBuilder() {
                return getHarvestResFieldBuilder().addBuilder(
                        com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.getDefaultInstance());
            }

            public com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.Builder addHarvestResBuilder(
                    int index) {
                return getHarvestResFieldBuilder().addBuilder(
                        index, com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.getDefaultInstance());
            }

            public java.util.List<com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.Builder>
            getHarvestResBuilderList() {
                return getHarvestResFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes, com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.Builder, com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_MesOrBuilder>
            getHarvestResFieldBuilder() {
                if (harvestResBuilder_ == null) {
                    harvestResBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes, com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.Builder, com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_MesOrBuilder>(
                            harvestRes_,
                            ((bitField0_ & 0x00000002) == 0x00000002),
                            getParentForChildren(),
                            isClean());
                    harvestRes_ = null;
                }
                return harvestResBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:Mine_Harvest_Query_Res)
        }

        // @@protoc_insertion_point(class_scope:Mine_Harvest_Query_Res)
    }

    // @@protoc_insertion_point(outer_class_scope)
}
