// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Pvp_Friend_Confirm_Res.proto

package com.pkuvr.game_server.proto.serverproto;

public final class Pvp_Friend_Confirm_Response {
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Pvp_Friend_Confirm_Res_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Pvp_Friend_Confirm_Res_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\034Pvp_Friend_Confirm_Res.proto\"h\n\026Pvp_Fr" +
                        "iend_Confirm_Res\022\021\n\terrorCode\030\001 \002(\005\022\024\n\014m" +
                        "atchSuccess\030\002 \001(\010\022\022\n\nclientTime\030\003 \001(\002\022\021\n" +
                        "\tmatchTime\030\004 \001(\005BD\n%com.pkuvr.game_server." +
                        "proto.serverprotoB\033Pvp_Friend_Confirm_Re" +
                        "sponse"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_Pvp_Friend_Confirm_Res_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_Pvp_Friend_Confirm_Res_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_Pvp_Friend_Confirm_Res_descriptor,
                                new String[]{"ErrorCode", "MatchSuccess", "ClientTime", "MatchTime",},
                                com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res.class,
                                com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    private Pvp_Friend_Confirm_Response() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface Pvp_Friend_Confirm_ResOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required int32 errorCode = 1;
        boolean hasErrorCode();

        int getErrorCode();

        // optional bool matchSuccess = 2;
        boolean hasMatchSuccess();

        boolean getMatchSuccess();

        // optional float clientTime = 3;
        boolean hasClientTime();

        float getClientTime();

        // optional int32 matchTime = 4;
        boolean hasMatchTime();

        int getMatchTime();
    }

    public static final class Pvp_Friend_Confirm_Res extends
            com.google.protobuf.GeneratedMessage
            implements Pvp_Friend_Confirm_ResOrBuilder {
        // required int32 errorCode = 1;
        public static final int ERRORCODE_FIELD_NUMBER = 1;
        // optional bool matchSuccess = 2;
        public static final int MATCHSUCCESS_FIELD_NUMBER = 2;
        // optional float clientTime = 3;
        public static final int CLIENTTIME_FIELD_NUMBER = 3;
        // optional int32 matchTime = 4;
        public static final int MATCHTIME_FIELD_NUMBER = 4;
        private static final Pvp_Friend_Confirm_Res defaultInstance;
        private static final long serialVersionUID = 0L;

        static {
            defaultInstance = new Pvp_Friend_Confirm_Res(true);
            defaultInstance.initFields();
        }

        private int bitField0_;
        private int errorCode_;
        private boolean matchSuccess_;
        private float clientTime_;
        private int matchTime_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Pvp_Friend_Confirm_Res.newBuilder() to construct.
        private Pvp_Friend_Confirm_Res(Builder builder) {
            super(builder);
        }

        private Pvp_Friend_Confirm_Res(boolean noInit) {
        }

        public static Pvp_Friend_Confirm_Res getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.internal_static_Pvp_Friend_Confirm_Res_descriptor;
        }

        public static com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Pvp_Friend_Confirm_Res getDefaultInstanceForType() {
            return defaultInstance;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.internal_static_Pvp_Friend_Confirm_Res_fieldAccessorTable;
        }

        public boolean hasErrorCode() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getErrorCode() {
            return errorCode_;
        }

        public boolean hasMatchSuccess() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public boolean getMatchSuccess() {
            return matchSuccess_;
        }

        public boolean hasClientTime() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public float getClientTime() {
            return clientTime_;
        }

        public boolean hasMatchTime() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public int getMatchTime() {
            return matchTime_;
        }

        private void initFields() {
            errorCode_ = 0;
            matchSuccess_ = false;
            clientTime_ = 0F;
            matchTime_ = 0;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasErrorCode()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, errorCode_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBool(2, matchSuccess_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeFloat(3, clientTime_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt32(4, matchTime_);
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, errorCode_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(2, matchSuccess_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(3, clientTime_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, matchTime_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_ResOrBuilder {
            private int bitField0_;
            // required int32 errorCode = 1;
            private int errorCode_;
            // optional bool matchSuccess = 2;
            private boolean matchSuccess_;
            // optional float clientTime = 3;
            private float clientTime_;
            // optional int32 matchTime = 4;
            private int matchTime_;

            // Construct using com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.internal_static_Pvp_Friend_Confirm_Res_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.internal_static_Pvp_Friend_Confirm_Res_fieldAccessorTable;
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                errorCode_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                matchSuccess_ = false;
                bitField0_ = (bitField0_ & ~0x00000002);
                clientTime_ = 0F;
                bitField0_ = (bitField0_ & ~0x00000004);
                matchTime_ = 0;
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res.getDescriptor();
            }

            public com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res getDefaultInstanceForType() {
                return com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res.getDefaultInstance();
            }

            public com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res build() {
                com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res buildPartial() {
                com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res result = new com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.errorCode_ = errorCode_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.matchSuccess_ = matchSuccess_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.clientTime_ = clientTime_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.matchTime_ = matchTime_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res) {
                    return mergeFrom((com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res other) {
                if (other == com.pkuvr.game_server.proto.serverproto.Pvp_Friend_Confirm_Response.Pvp_Friend_Confirm_Res.getDefaultInstance())
                    return this;
                if (other.hasErrorCode()) {
                    setErrorCode(other.getErrorCode());
                }
                if (other.hasMatchSuccess()) {
                    setMatchSuccess(other.getMatchSuccess());
                }
                if (other.hasClientTime()) {
                    setClientTime(other.getClientTime());
                }
                if (other.hasMatchTime()) {
                    setMatchTime(other.getMatchTime());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasErrorCode()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            errorCode_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            matchSuccess_ = input.readBool();
                            break;
                        }
                        case 29: {
                            bitField0_ |= 0x00000004;
                            clientTime_ = input.readFloat();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            matchTime_ = input.readInt32();
                            break;
                        }
                    }
                }
            }

            public boolean hasErrorCode() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getErrorCode() {
                return errorCode_;
            }

            public Builder setErrorCode(int value) {
                bitField0_ |= 0x00000001;
                errorCode_ = value;
                onChanged();
                return this;
            }

            public Builder clearErrorCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                errorCode_ = 0;
                onChanged();
                return this;
            }

            public boolean hasMatchSuccess() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public boolean getMatchSuccess() {
                return matchSuccess_;
            }

            public Builder setMatchSuccess(boolean value) {
                bitField0_ |= 0x00000002;
                matchSuccess_ = value;
                onChanged();
                return this;
            }

            public Builder clearMatchSuccess() {
                bitField0_ = (bitField0_ & ~0x00000002);
                matchSuccess_ = false;
                onChanged();
                return this;
            }

            public boolean hasClientTime() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public float getClientTime() {
                return clientTime_;
            }

            public Builder setClientTime(float value) {
                bitField0_ |= 0x00000004;
                clientTime_ = value;
                onChanged();
                return this;
            }

            public Builder clearClientTime() {
                bitField0_ = (bitField0_ & ~0x00000004);
                clientTime_ = 0F;
                onChanged();
                return this;
            }

            public boolean hasMatchTime() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            public int getMatchTime() {
                return matchTime_;
            }

            public Builder setMatchTime(int value) {
                bitField0_ |= 0x00000008;
                matchTime_ = value;
                onChanged();
                return this;
            }

            public Builder clearMatchTime() {
                bitField0_ = (bitField0_ & ~0x00000008);
                matchTime_ = 0;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Pvp_Friend_Confirm_Res)
        }

        // @@protoc_insertion_point(class_scope:Pvp_Friend_Confirm_Res)
    }

    // @@protoc_insertion_point(outer_class_scope)
}
