// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Zone_Defense_Info_Res.proto

package com.pkuvr.game_server.proto.serverproto;

public final class Zone_Defense_Info_Response {
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Zone_Defense_Info_Res_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Zone_Defense_Info_Res_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\033Zone_Defense_Info_Res.proto\032\024BI_Battle" +
                        "_Unit.proto\032\035BI_Battle_Unit_Position.pro" +
                        "to\"\372\001\n\025Zone_Defense_Info_Res\022\021\n\terrorCod" +
                        "e\030\001 \002(\005\022\033\n\023headerquartersLevel\030\002 \001(\005\022-\n\016" +
                        "battleUnitInfo\030\003 \003(\0132\025.Battle_Unit_Posit" +
                        "ion\022\031\n\021blockHouseNPCInfo\030\004 \001(\t\022\034\n\024comman" +
                        "derInstruction\030\005 \001(\005\022\024\n\014landMineInfo\030\006 \001" +
                        "(\t\022\036\n\010unitInfo\030\007 \003(\0132\014.Battle_Unit\022\023\n\013is" +
                        "Protected\030\010 \001(\010BC\n%com.pkuvr.game_server.p" +
                        "roto.serverprotoB\032Zone_Defense_Info_Resp",
                "onse"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_Zone_Defense_Info_Res_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_Zone_Defense_Info_Res_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_Zone_Defense_Info_Res_descriptor,
                                new String[]{"ErrorCode", "HeaderquartersLevel", "BattleUnitInfo", "BlockHouseNPCInfo", "CommanderInstruction", "LandMineInfo", "UnitInfo", "IsProtected",},
                                com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res.class,
                                com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.pkuvr.game_server.proto.commons.BI_Battle_Unit.getDescriptor(),
                                com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.getDescriptor(),
                        }, assigner);
    }

    private Zone_Defense_Info_Response() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface Zone_Defense_Info_ResOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required int32 errorCode = 1;
        boolean hasErrorCode();

        int getErrorCode();

        // optional int32 headerquartersLevel = 2;
        boolean hasHeaderquartersLevel();

        int getHeaderquartersLevel();

        // repeated .Battle_Unit_Position battleUnitInfo = 3;
        java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position>
        getBattleUnitInfoList();

        com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position getBattleUnitInfo(int index);

        int getBattleUnitInfoCount();

        java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_PositionOrBuilder>
        getBattleUnitInfoOrBuilderList();

        com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_PositionOrBuilder getBattleUnitInfoOrBuilder(
                int index);

        // optional string blockHouseNPCInfo = 4;
        boolean hasBlockHouseNPCInfo();

        String getBlockHouseNPCInfo();

        // optional int32 commanderInstruction = 5;
        boolean hasCommanderInstruction();

        int getCommanderInstruction();

        // optional string landMineInfo = 6;
        boolean hasLandMineInfo();

        String getLandMineInfo();

        // repeated .Battle_Unit unitInfo = 7;
        java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit>
        getUnitInfoList();

        com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit getUnitInfo(int index);

        int getUnitInfoCount();

        java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_UnitOrBuilder>
        getUnitInfoOrBuilderList();

        com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_UnitOrBuilder getUnitInfoOrBuilder(
                int index);

        // optional bool isProtected = 8;
        boolean hasIsProtected();

        boolean getIsProtected();
    }

    public static final class Zone_Defense_Info_Res extends
            com.google.protobuf.GeneratedMessage
            implements Zone_Defense_Info_ResOrBuilder {
        // required int32 errorCode = 1;
        public static final int ERRORCODE_FIELD_NUMBER = 1;
        // optional int32 headerquartersLevel = 2;
        public static final int HEADERQUARTERSLEVEL_FIELD_NUMBER = 2;
        // repeated .Battle_Unit_Position battleUnitInfo = 3;
        public static final int BATTLEUNITINFO_FIELD_NUMBER = 3;
        // optional string blockHouseNPCInfo = 4;
        public static final int BLOCKHOUSENPCINFO_FIELD_NUMBER = 4;
        // optional int32 commanderInstruction = 5;
        public static final int COMMANDERINSTRUCTION_FIELD_NUMBER = 5;
        // optional string landMineInfo = 6;
        public static final int LANDMINEINFO_FIELD_NUMBER = 6;
        // repeated .Battle_Unit unitInfo = 7;
        public static final int UNITINFO_FIELD_NUMBER = 7;
        // optional bool isProtected = 8;
        public static final int ISPROTECTED_FIELD_NUMBER = 8;
        private static final Zone_Defense_Info_Res defaultInstance;
        private static final long serialVersionUID = 0L;

        static {
            defaultInstance = new Zone_Defense_Info_Res(true);
            defaultInstance.initFields();
        }

        private int bitField0_;
        private int errorCode_;
        private int headerquartersLevel_;
        private java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position> battleUnitInfo_;
        private Object blockHouseNPCInfo_;
        private int commanderInstruction_;
        private Object landMineInfo_;
        private java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit> unitInfo_;
        private boolean isProtected_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Zone_Defense_Info_Res.newBuilder() to construct.
        private Zone_Defense_Info_Res(Builder builder) {
            super(builder);
        }

        private Zone_Defense_Info_Res(boolean noInit) {
        }

        public static Zone_Defense_Info_Res getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.internal_static_Zone_Defense_Info_Res_descriptor;
        }

        public static com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Zone_Defense_Info_Res getDefaultInstanceForType() {
            return defaultInstance;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.internal_static_Zone_Defense_Info_Res_fieldAccessorTable;
        }

        public boolean hasErrorCode() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getErrorCode() {
            return errorCode_;
        }

        public boolean hasHeaderquartersLevel() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public int getHeaderquartersLevel() {
            return headerquartersLevel_;
        }

        public java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position> getBattleUnitInfoList() {
            return battleUnitInfo_;
        }

        public java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_PositionOrBuilder>
        getBattleUnitInfoOrBuilderList() {
            return battleUnitInfo_;
        }

        public int getBattleUnitInfoCount() {
            return battleUnitInfo_.size();
        }

        public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position getBattleUnitInfo(int index) {
            return battleUnitInfo_.get(index);
        }

        public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_PositionOrBuilder getBattleUnitInfoOrBuilder(
                int index) {
            return battleUnitInfo_.get(index);
        }

        public boolean hasBlockHouseNPCInfo() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public String getBlockHouseNPCInfo() {
            Object ref = blockHouseNPCInfo_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    blockHouseNPCInfo_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getBlockHouseNPCInfoBytes() {
            Object ref = blockHouseNPCInfo_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                blockHouseNPCInfo_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public boolean hasCommanderInstruction() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public int getCommanderInstruction() {
            return commanderInstruction_;
        }

        public boolean hasLandMineInfo() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        public String getLandMineInfo() {
            Object ref = landMineInfo_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    landMineInfo_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getLandMineInfoBytes() {
            Object ref = landMineInfo_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                landMineInfo_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit> getUnitInfoList() {
            return unitInfo_;
        }

        public java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_UnitOrBuilder>
        getUnitInfoOrBuilderList() {
            return unitInfo_;
        }

        public int getUnitInfoCount() {
            return unitInfo_.size();
        }

        public com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit getUnitInfo(int index) {
            return unitInfo_.get(index);
        }

        public com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_UnitOrBuilder getUnitInfoOrBuilder(
                int index) {
            return unitInfo_.get(index);
        }

        public boolean hasIsProtected() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }

        public boolean getIsProtected() {
            return isProtected_;
        }

        private void initFields() {
            errorCode_ = 0;
            headerquartersLevel_ = 0;
            battleUnitInfo_ = java.util.Collections.emptyList();
            blockHouseNPCInfo_ = "";
            commanderInstruction_ = 0;
            landMineInfo_ = "";
            unitInfo_ = java.util.Collections.emptyList();
            isProtected_ = false;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasErrorCode()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, errorCode_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, headerquartersLevel_);
            }
            for (int i = 0; i < battleUnitInfo_.size(); i++) {
                output.writeMessage(3, battleUnitInfo_.get(i));
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(4, getBlockHouseNPCInfoBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt32(5, commanderInstruction_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeBytes(6, getLandMineInfoBytes());
            }
            for (int i = 0; i < unitInfo_.size(); i++) {
                output.writeMessage(7, unitInfo_.get(i));
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeBool(8, isProtected_);
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, errorCode_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, headerquartersLevel_);
            }
            for (int i = 0; i < battleUnitInfo_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, battleUnitInfo_.get(i));
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, getBlockHouseNPCInfoBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(5, commanderInstruction_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(6, getLandMineInfoBytes());
            }
            for (int i = 0; i < unitInfo_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(7, unitInfo_.get(i));
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(8, isProtected_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_ResOrBuilder {
            private int bitField0_;
            // required int32 errorCode = 1;
            private int errorCode_;
            // optional int32 headerquartersLevel = 2;
            private int headerquartersLevel_;
            // repeated .Battle_Unit_Position battleUnitInfo = 3;
            private java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position> battleUnitInfo_ =
                    java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilder<
                    com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position.Builder, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_PositionOrBuilder> battleUnitInfoBuilder_;
            // optional string blockHouseNPCInfo = 4;
            private Object blockHouseNPCInfo_ = "";
            // optional int32 commanderInstruction = 5;
            private int commanderInstruction_;
            // optional string landMineInfo = 6;
            private Object landMineInfo_ = "";
            // repeated .Battle_Unit unitInfo = 7;
            private java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit> unitInfo_ =
                    java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilder<
                    com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit, com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit.Builder, com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_UnitOrBuilder> unitInfoBuilder_;
            // optional bool isProtected = 8;
            private boolean isProtected_;

            // Construct using com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.internal_static_Zone_Defense_Info_Res_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.internal_static_Zone_Defense_Info_Res_fieldAccessorTable;
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getBattleUnitInfoFieldBuilder();
                    getUnitInfoFieldBuilder();
                }
            }

            public Builder clear() {
                super.clear();
                errorCode_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                headerquartersLevel_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                if (battleUnitInfoBuilder_ == null) {
                    battleUnitInfo_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                } else {
                    battleUnitInfoBuilder_.clear();
                }
                blockHouseNPCInfo_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                commanderInstruction_ = 0;
                bitField0_ = (bitField0_ & ~0x00000010);
                landMineInfo_ = "";
                bitField0_ = (bitField0_ & ~0x00000020);
                if (unitInfoBuilder_ == null) {
                    unitInfo_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000040);
                } else {
                    unitInfoBuilder_.clear();
                }
                isProtected_ = false;
                bitField0_ = (bitField0_ & ~0x00000080);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res.getDescriptor();
            }

            public com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res getDefaultInstanceForType() {
                return com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res.getDefaultInstance();
            }

            public com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res build() {
                com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res buildPartial() {
                com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res result = new com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.errorCode_ = errorCode_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.headerquartersLevel_ = headerquartersLevel_;
                if (battleUnitInfoBuilder_ == null) {
                    if (((bitField0_ & 0x00000004) == 0x00000004)) {
                        battleUnitInfo_ = java.util.Collections.unmodifiableList(battleUnitInfo_);
                        bitField0_ = (bitField0_ & ~0x00000004);
                    }
                    result.battleUnitInfo_ = battleUnitInfo_;
                } else {
                    result.battleUnitInfo_ = battleUnitInfoBuilder_.build();
                }
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.blockHouseNPCInfo_ = blockHouseNPCInfo_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.commanderInstruction_ = commanderInstruction_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.landMineInfo_ = landMineInfo_;
                if (unitInfoBuilder_ == null) {
                    if (((bitField0_ & 0x00000040) == 0x00000040)) {
                        unitInfo_ = java.util.Collections.unmodifiableList(unitInfo_);
                        bitField0_ = (bitField0_ & ~0x00000040);
                    }
                    result.unitInfo_ = unitInfo_;
                } else {
                    result.unitInfo_ = unitInfoBuilder_.build();
                }
                if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.isProtected_ = isProtected_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res) {
                    return mergeFrom((com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res other) {
                if (other == com.pkuvr.game_server.proto.serverproto.Zone_Defense_Info_Response.Zone_Defense_Info_Res.getDefaultInstance())
                    return this;
                if (other.hasErrorCode()) {
                    setErrorCode(other.getErrorCode());
                }
                if (other.hasHeaderquartersLevel()) {
                    setHeaderquartersLevel(other.getHeaderquartersLevel());
                }
                if (battleUnitInfoBuilder_ == null) {
                    if (!other.battleUnitInfo_.isEmpty()) {
                        if (battleUnitInfo_.isEmpty()) {
                            battleUnitInfo_ = other.battleUnitInfo_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                        } else {
                            ensureBattleUnitInfoIsMutable();
                            battleUnitInfo_.addAll(other.battleUnitInfo_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.battleUnitInfo_.isEmpty()) {
                        if (battleUnitInfoBuilder_.isEmpty()) {
                            battleUnitInfoBuilder_.dispose();
                            battleUnitInfoBuilder_ = null;
                            battleUnitInfo_ = other.battleUnitInfo_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                            battleUnitInfoBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getBattleUnitInfoFieldBuilder() : null;
                        } else {
                            battleUnitInfoBuilder_.addAllMessages(other.battleUnitInfo_);
                        }
                    }
                }
                if (other.hasBlockHouseNPCInfo()) {
                    setBlockHouseNPCInfo(other.getBlockHouseNPCInfo());
                }
                if (other.hasCommanderInstruction()) {
                    setCommanderInstruction(other.getCommanderInstruction());
                }
                if (other.hasLandMineInfo()) {
                    setLandMineInfo(other.getLandMineInfo());
                }
                if (unitInfoBuilder_ == null) {
                    if (!other.unitInfo_.isEmpty()) {
                        if (unitInfo_.isEmpty()) {
                            unitInfo_ = other.unitInfo_;
                            bitField0_ = (bitField0_ & ~0x00000040);
                        } else {
                            ensureUnitInfoIsMutable();
                            unitInfo_.addAll(other.unitInfo_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.unitInfo_.isEmpty()) {
                        if (unitInfoBuilder_.isEmpty()) {
                            unitInfoBuilder_.dispose();
                            unitInfoBuilder_ = null;
                            unitInfo_ = other.unitInfo_;
                            bitField0_ = (bitField0_ & ~0x00000040);
                            unitInfoBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getUnitInfoFieldBuilder() : null;
                        } else {
                            unitInfoBuilder_.addAllMessages(other.unitInfo_);
                        }
                    }
                }
                if (other.hasIsProtected()) {
                    setIsProtected(other.getIsProtected());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasErrorCode()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            errorCode_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            headerquartersLevel_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position.Builder subBuilder = com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position.newBuilder();
                            input.readMessage(subBuilder, extensionRegistry);
                            addBattleUnitInfo(subBuilder.buildPartial());
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000008;
                            blockHouseNPCInfo_ = input.readBytes();
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000010;
                            commanderInstruction_ = input.readInt32();
                            break;
                        }
                        case 50: {
                            bitField0_ |= 0x00000020;
                            landMineInfo_ = input.readBytes();
                            break;
                        }
                        case 58: {
                            com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit.Builder subBuilder = com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit.newBuilder();
                            input.readMessage(subBuilder, extensionRegistry);
                            addUnitInfo(subBuilder.buildPartial());
                            break;
                        }
                        case 64: {
                            bitField0_ |= 0x00000080;
                            isProtected_ = input.readBool();
                            break;
                        }
                    }
                }
            }

            public boolean hasErrorCode() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getErrorCode() {
                return errorCode_;
            }

            public Builder setErrorCode(int value) {
                bitField0_ |= 0x00000001;
                errorCode_ = value;
                onChanged();
                return this;
            }

            public Builder clearErrorCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                errorCode_ = 0;
                onChanged();
                return this;
            }

            public boolean hasHeaderquartersLevel() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public int getHeaderquartersLevel() {
                return headerquartersLevel_;
            }

            public Builder setHeaderquartersLevel(int value) {
                bitField0_ |= 0x00000002;
                headerquartersLevel_ = value;
                onChanged();
                return this;
            }

            public Builder clearHeaderquartersLevel() {
                bitField0_ = (bitField0_ & ~0x00000002);
                headerquartersLevel_ = 0;
                onChanged();
                return this;
            }

            private void ensureBattleUnitInfoIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    battleUnitInfo_ = new java.util.ArrayList<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position>(battleUnitInfo_);
                    bitField0_ |= 0x00000004;
                }
            }

            public java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position> getBattleUnitInfoList() {
                if (battleUnitInfoBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(battleUnitInfo_);
                } else {
                    return battleUnitInfoBuilder_.getMessageList();
                }
            }

            public int getBattleUnitInfoCount() {
                if (battleUnitInfoBuilder_ == null) {
                    return battleUnitInfo_.size();
                } else {
                    return battleUnitInfoBuilder_.getCount();
                }
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position getBattleUnitInfo(int index) {
                if (battleUnitInfoBuilder_ == null) {
                    return battleUnitInfo_.get(index);
                } else {
                    return battleUnitInfoBuilder_.getMessage(index);
                }
            }

            public Builder setBattleUnitInfo(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position value) {
                if (battleUnitInfoBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureBattleUnitInfoIsMutable();
                    battleUnitInfo_.set(index, value);
                    onChanged();
                } else {
                    battleUnitInfoBuilder_.setMessage(index, value);
                }
                return this;
            }

            public Builder setBattleUnitInfo(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position.Builder builderForValue) {
                if (battleUnitInfoBuilder_ == null) {
                    ensureBattleUnitInfoIsMutable();
                    battleUnitInfo_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    battleUnitInfoBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addBattleUnitInfo(com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position value) {
                if (battleUnitInfoBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureBattleUnitInfoIsMutable();
                    battleUnitInfo_.add(value);
                    onChanged();
                } else {
                    battleUnitInfoBuilder_.addMessage(value);
                }
                return this;
            }

            public Builder addBattleUnitInfo(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position value) {
                if (battleUnitInfoBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureBattleUnitInfoIsMutable();
                    battleUnitInfo_.add(index, value);
                    onChanged();
                } else {
                    battleUnitInfoBuilder_.addMessage(index, value);
                }
                return this;
            }

            public Builder addBattleUnitInfo(
                    com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position.Builder builderForValue) {
                if (battleUnitInfoBuilder_ == null) {
                    ensureBattleUnitInfoIsMutable();
                    battleUnitInfo_.add(builderForValue.build());
                    onChanged();
                } else {
                    battleUnitInfoBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            public Builder addBattleUnitInfo(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position.Builder builderForValue) {
                if (battleUnitInfoBuilder_ == null) {
                    ensureBattleUnitInfoIsMutable();
                    battleUnitInfo_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    battleUnitInfoBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addAllBattleUnitInfo(
                    Iterable<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position> values) {
                if (battleUnitInfoBuilder_ == null) {
                    ensureBattleUnitInfoIsMutable();
                    super.addAll(values, battleUnitInfo_);
                    onChanged();
                } else {
                    battleUnitInfoBuilder_.addAllMessages(values);
                }
                return this;
            }

            public Builder clearBattleUnitInfo() {
                if (battleUnitInfoBuilder_ == null) {
                    battleUnitInfo_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                    onChanged();
                } else {
                    battleUnitInfoBuilder_.clear();
                }
                return this;
            }

            public Builder removeBattleUnitInfo(int index) {
                if (battleUnitInfoBuilder_ == null) {
                    ensureBattleUnitInfoIsMutable();
                    battleUnitInfo_.remove(index);
                    onChanged();
                } else {
                    battleUnitInfoBuilder_.remove(index);
                }
                return this;
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position.Builder getBattleUnitInfoBuilder(
                    int index) {
                return getBattleUnitInfoFieldBuilder().getBuilder(index);
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_PositionOrBuilder getBattleUnitInfoOrBuilder(
                    int index) {
                if (battleUnitInfoBuilder_ == null) {
                    return battleUnitInfo_.get(index);
                } else {
                    return battleUnitInfoBuilder_.getMessageOrBuilder(index);
                }
            }

            public java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_PositionOrBuilder>
            getBattleUnitInfoOrBuilderList() {
                if (battleUnitInfoBuilder_ != null) {
                    return battleUnitInfoBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(battleUnitInfo_);
                }
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position.Builder addBattleUnitInfoBuilder() {
                return getBattleUnitInfoFieldBuilder().addBuilder(
                        com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position.getDefaultInstance());
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position.Builder addBattleUnitInfoBuilder(
                    int index) {
                return getBattleUnitInfoFieldBuilder().addBuilder(
                        index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position.getDefaultInstance());
            }

            public java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position.Builder>
            getBattleUnitInfoBuilderList() {
                return getBattleUnitInfoFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position.Builder, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_PositionOrBuilder>
            getBattleUnitInfoFieldBuilder() {
                if (battleUnitInfoBuilder_ == null) {
                    battleUnitInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_Position.Builder, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Position.Battle_Unit_PositionOrBuilder>(
                            battleUnitInfo_,
                            ((bitField0_ & 0x00000004) == 0x00000004),
                            getParentForChildren(),
                            isClean());
                    battleUnitInfo_ = null;
                }
                return battleUnitInfoBuilder_;
            }

            public boolean hasBlockHouseNPCInfo() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            public String getBlockHouseNPCInfo() {
                Object ref = blockHouseNPCInfo_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    blockHouseNPCInfo_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            void setBlockHouseNPCInfo(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000008;
                blockHouseNPCInfo_ = value;
                onChanged();
            }

            public Builder setBlockHouseNPCInfo(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                blockHouseNPCInfo_ = value;
                onChanged();
                return this;
            }

            public Builder clearBlockHouseNPCInfo() {
                bitField0_ = (bitField0_ & ~0x00000008);
                blockHouseNPCInfo_ = getDefaultInstance().getBlockHouseNPCInfo();
                onChanged();
                return this;
            }

            public boolean hasCommanderInstruction() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            public int getCommanderInstruction() {
                return commanderInstruction_;
            }

            public Builder setCommanderInstruction(int value) {
                bitField0_ |= 0x00000010;
                commanderInstruction_ = value;
                onChanged();
                return this;
            }

            public Builder clearCommanderInstruction() {
                bitField0_ = (bitField0_ & ~0x00000010);
                commanderInstruction_ = 0;
                onChanged();
                return this;
            }

            public boolean hasLandMineInfo() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            public String getLandMineInfo() {
                Object ref = landMineInfo_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    landMineInfo_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            void setLandMineInfo(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000020;
                landMineInfo_ = value;
                onChanged();
            }

            public Builder setLandMineInfo(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000020;
                landMineInfo_ = value;
                onChanged();
                return this;
            }

            public Builder clearLandMineInfo() {
                bitField0_ = (bitField0_ & ~0x00000020);
                landMineInfo_ = getDefaultInstance().getLandMineInfo();
                onChanged();
                return this;
            }

            private void ensureUnitInfoIsMutable() {
                if (!((bitField0_ & 0x00000040) == 0x00000040)) {
                    unitInfo_ = new java.util.ArrayList<com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit>(unitInfo_);
                    bitField0_ |= 0x00000040;
                }
            }

            public java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit> getUnitInfoList() {
                if (unitInfoBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(unitInfo_);
                } else {
                    return unitInfoBuilder_.getMessageList();
                }
            }

            public int getUnitInfoCount() {
                if (unitInfoBuilder_ == null) {
                    return unitInfo_.size();
                } else {
                    return unitInfoBuilder_.getCount();
                }
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit getUnitInfo(int index) {
                if (unitInfoBuilder_ == null) {
                    return unitInfo_.get(index);
                } else {
                    return unitInfoBuilder_.getMessage(index);
                }
            }

            public Builder setUnitInfo(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit value) {
                if (unitInfoBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureUnitInfoIsMutable();
                    unitInfo_.set(index, value);
                    onChanged();
                } else {
                    unitInfoBuilder_.setMessage(index, value);
                }
                return this;
            }

            public Builder setUnitInfo(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit.Builder builderForValue) {
                if (unitInfoBuilder_ == null) {
                    ensureUnitInfoIsMutable();
                    unitInfo_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    unitInfoBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addUnitInfo(com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit value) {
                if (unitInfoBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureUnitInfoIsMutable();
                    unitInfo_.add(value);
                    onChanged();
                } else {
                    unitInfoBuilder_.addMessage(value);
                }
                return this;
            }

            public Builder addUnitInfo(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit value) {
                if (unitInfoBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureUnitInfoIsMutable();
                    unitInfo_.add(index, value);
                    onChanged();
                } else {
                    unitInfoBuilder_.addMessage(index, value);
                }
                return this;
            }

            public Builder addUnitInfo(
                    com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit.Builder builderForValue) {
                if (unitInfoBuilder_ == null) {
                    ensureUnitInfoIsMutable();
                    unitInfo_.add(builderForValue.build());
                    onChanged();
                } else {
                    unitInfoBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            public Builder addUnitInfo(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit.Builder builderForValue) {
                if (unitInfoBuilder_ == null) {
                    ensureUnitInfoIsMutable();
                    unitInfo_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    unitInfoBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addAllUnitInfo(
                    Iterable<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit> values) {
                if (unitInfoBuilder_ == null) {
                    ensureUnitInfoIsMutable();
                    super.addAll(values, unitInfo_);
                    onChanged();
                } else {
                    unitInfoBuilder_.addAllMessages(values);
                }
                return this;
            }

            public Builder clearUnitInfo() {
                if (unitInfoBuilder_ == null) {
                    unitInfo_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000040);
                    onChanged();
                } else {
                    unitInfoBuilder_.clear();
                }
                return this;
            }

            public Builder removeUnitInfo(int index) {
                if (unitInfoBuilder_ == null) {
                    ensureUnitInfoIsMutable();
                    unitInfo_.remove(index);
                    onChanged();
                } else {
                    unitInfoBuilder_.remove(index);
                }
                return this;
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit.Builder getUnitInfoBuilder(
                    int index) {
                return getUnitInfoFieldBuilder().getBuilder(index);
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_UnitOrBuilder getUnitInfoOrBuilder(
                    int index) {
                if (unitInfoBuilder_ == null) {
                    return unitInfo_.get(index);
                } else {
                    return unitInfoBuilder_.getMessageOrBuilder(index);
                }
            }

            public java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_UnitOrBuilder>
            getUnitInfoOrBuilderList() {
                if (unitInfoBuilder_ != null) {
                    return unitInfoBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(unitInfo_);
                }
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit.Builder addUnitInfoBuilder() {
                return getUnitInfoFieldBuilder().addBuilder(
                        com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit.getDefaultInstance());
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit.Builder addUnitInfoBuilder(
                    int index) {
                return getUnitInfoFieldBuilder().addBuilder(
                        index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit.getDefaultInstance());
            }

            public java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit.Builder>
            getUnitInfoBuilderList() {
                return getUnitInfoFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit, com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit.Builder, com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_UnitOrBuilder>
            getUnitInfoFieldBuilder() {
                if (unitInfoBuilder_ == null) {
                    unitInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit, com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_Unit.Builder, com.pkuvr.game_server.proto.commons.BI_Battle_Unit.Battle_UnitOrBuilder>(
                            unitInfo_,
                            ((bitField0_ & 0x00000040) == 0x00000040),
                            getParentForChildren(),
                            isClean());
                    unitInfo_ = null;
                }
                return unitInfoBuilder_;
            }

            public boolean hasIsProtected() {
                return ((bitField0_ & 0x00000080) == 0x00000080);
            }

            public boolean getIsProtected() {
                return isProtected_;
            }

            public Builder setIsProtected(boolean value) {
                bitField0_ |= 0x00000080;
                isProtected_ = value;
                onChanged();
                return this;
            }

            public Builder clearIsProtected() {
                bitField0_ = (bitField0_ & ~0x00000080);
                isProtected_ = false;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Zone_Defense_Info_Res)
        }

        // @@protoc_insertion_point(class_scope:Zone_Defense_Info_Res)
    }

    // @@protoc_insertion_point(outer_class_scope)
}
