// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BI_Mine_Resource.proto

package com.pkuvr.game_server.proto.commons;

public final class BI_Mine_Resource {
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Mine_Resource_Mes_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Mine_Resource_Mes_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\026BI_Mine_Resource.proto\"\242\001\n\021Mine_Resour" +
                        "ce_Mes\022\026\n\016produceResType\030\001 \001(\005\022\022\n\nproduc" +
                        "eNum\030\002 \001(\005\022\026\n\016isMineCarDrive\030\003 \001(\010\022\027\n\017mi" +
                        "neResourceNum\030\004 \001(\005\022\025\n\rproduceMuduls\030\005 \001" +
                        "(\005\022\031\n\021produceNumPerhour\030\006 \001(\005B5\n!com.gfa" +
                        "n.gameserver.proto.commonsB\020BI_Mine_Reso" +
                        "urce"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_Mine_Resource_Mes_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_Mine_Resource_Mes_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_Mine_Resource_Mes_descriptor,
                                new String[]{"ProduceResType", "ProduceNum", "IsMineCarDrive", "MineResourceNum", "ProduceMuduls", "ProduceNumPerhour",},
                                com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.class,
                                com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    private BI_Mine_Resource() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface Mine_Resource_MesOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional int32 produceResType = 1;
        boolean hasProduceResType();

        int getProduceResType();

        // optional int32 produceNum = 2;
        boolean hasProduceNum();

        int getProduceNum();

        // optional bool isMineCarDrive = 3;
        boolean hasIsMineCarDrive();

        boolean getIsMineCarDrive();

        // optional int32 mineResourceNum = 4;
        boolean hasMineResourceNum();

        int getMineResourceNum();

        // optional int32 produceMuduls = 5;
        boolean hasProduceMuduls();

        int getProduceMuduls();

        // optional int32 produceNumPerhour = 6;
        boolean hasProduceNumPerhour();

        int getProduceNumPerhour();
    }

    public static final class Mine_Resource_Mes extends
            com.google.protobuf.GeneratedMessage
            implements Mine_Resource_MesOrBuilder {
        // optional int32 produceResType = 1;
        public static final int PRODUCERESTYPE_FIELD_NUMBER = 1;
        // optional int32 produceNum = 2;
        public static final int PRODUCENUM_FIELD_NUMBER = 2;
        // optional bool isMineCarDrive = 3;
        public static final int ISMINECARDRIVE_FIELD_NUMBER = 3;
        // optional int32 mineResourceNum = 4;
        public static final int MINERESOURCENUM_FIELD_NUMBER = 4;
        // optional int32 produceMuduls = 5;
        public static final int PRODUCEMUDULS_FIELD_NUMBER = 5;
        // optional int32 produceNumPerhour = 6;
        public static final int PRODUCENUMPERHOUR_FIELD_NUMBER = 6;
        private static final Mine_Resource_Mes defaultInstance;
        private static final long serialVersionUID = 0L;

        static {
            defaultInstance = new Mine_Resource_Mes(true);
            defaultInstance.initFields();
        }

        private int bitField0_;
        private int produceResType_;
        private int produceNum_;
        private boolean isMineCarDrive_;
        private int mineResourceNum_;
        private int produceMuduls_;
        private int produceNumPerhour_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Mine_Resource_Mes.newBuilder() to construct.
        private Mine_Resource_Mes(Builder builder) {
            super(builder);
        }

        private Mine_Resource_Mes(boolean noInit) {
        }

        public static Mine_Resource_Mes getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.pkuvr.game_server.proto.commons.BI_Mine_Resource.internal_static_Mine_Resource_Mes_descriptor;
        }

        public static com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Mine_Resource_Mes getDefaultInstanceForType() {
            return defaultInstance;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.pkuvr.game_server.proto.commons.BI_Mine_Resource.internal_static_Mine_Resource_Mes_fieldAccessorTable;
        }

        public boolean hasProduceResType() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getProduceResType() {
            return produceResType_;
        }

        public boolean hasProduceNum() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public int getProduceNum() {
            return produceNum_;
        }

        public boolean hasIsMineCarDrive() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public boolean getIsMineCarDrive() {
            return isMineCarDrive_;
        }

        public boolean hasMineResourceNum() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public int getMineResourceNum() {
            return mineResourceNum_;
        }

        public boolean hasProduceMuduls() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        public int getProduceMuduls() {
            return produceMuduls_;
        }

        public boolean hasProduceNumPerhour() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }

        public int getProduceNumPerhour() {
            return produceNumPerhour_;
        }

        private void initFields() {
            produceResType_ = 0;
            produceNum_ = 0;
            isMineCarDrive_ = false;
            mineResourceNum_ = 0;
            produceMuduls_ = 0;
            produceNumPerhour_ = 0;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, produceResType_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, produceNum_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBool(3, isMineCarDrive_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt32(4, mineResourceNum_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeInt32(5, produceMuduls_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeInt32(6, produceNumPerhour_);
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, produceResType_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, produceNum_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(3, isMineCarDrive_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, mineResourceNum_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(5, produceMuduls_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(6, produceNumPerhour_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_MesOrBuilder {
            private int bitField0_;
            // optional int32 produceResType = 1;
            private int produceResType_;
            // optional int32 produceNum = 2;
            private int produceNum_;
            // optional bool isMineCarDrive = 3;
            private boolean isMineCarDrive_;
            // optional int32 mineResourceNum = 4;
            private int mineResourceNum_;
            // optional int32 produceMuduls = 5;
            private int produceMuduls_;
            // optional int32 produceNumPerhour = 6;
            private int produceNumPerhour_;

            // Construct using com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.pkuvr.game_server.proto.commons.BI_Mine_Resource.internal_static_Mine_Resource_Mes_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.pkuvr.game_server.proto.commons.BI_Mine_Resource.internal_static_Mine_Resource_Mes_fieldAccessorTable;
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                produceResType_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                produceNum_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                isMineCarDrive_ = false;
                bitField0_ = (bitField0_ & ~0x00000004);
                mineResourceNum_ = 0;
                bitField0_ = (bitField0_ & ~0x00000008);
                produceMuduls_ = 0;
                bitField0_ = (bitField0_ & ~0x00000010);
                produceNumPerhour_ = 0;
                bitField0_ = (bitField0_ & ~0x00000020);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.getDescriptor();
            }

            public com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes getDefaultInstanceForType() {
                return com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.getDefaultInstance();
            }

            public com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes build() {
                com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes buildPartial() {
                com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes result = new com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.produceResType_ = produceResType_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.produceNum_ = produceNum_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.isMineCarDrive_ = isMineCarDrive_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.mineResourceNum_ = mineResourceNum_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.produceMuduls_ = produceMuduls_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.produceNumPerhour_ = produceNumPerhour_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes) {
                    return mergeFrom((com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes other) {
                if (other == com.pkuvr.game_server.proto.commons.BI_Mine_Resource.Mine_Resource_Mes.getDefaultInstance())
                    return this;
                if (other.hasProduceResType()) {
                    setProduceResType(other.getProduceResType());
                }
                if (other.hasProduceNum()) {
                    setProduceNum(other.getProduceNum());
                }
                if (other.hasIsMineCarDrive()) {
                    setIsMineCarDrive(other.getIsMineCarDrive());
                }
                if (other.hasMineResourceNum()) {
                    setMineResourceNum(other.getMineResourceNum());
                }
                if (other.hasProduceMuduls()) {
                    setProduceMuduls(other.getProduceMuduls());
                }
                if (other.hasProduceNumPerhour()) {
                    setProduceNumPerhour(other.getProduceNumPerhour());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            produceResType_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            produceNum_ = input.readInt32();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            isMineCarDrive_ = input.readBool();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            mineResourceNum_ = input.readInt32();
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000010;
                            produceMuduls_ = input.readInt32();
                            break;
                        }
                        case 48: {
                            bitField0_ |= 0x00000020;
                            produceNumPerhour_ = input.readInt32();
                            break;
                        }
                    }
                }
            }

            public boolean hasProduceResType() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getProduceResType() {
                return produceResType_;
            }

            public Builder setProduceResType(int value) {
                bitField0_ |= 0x00000001;
                produceResType_ = value;
                onChanged();
                return this;
            }

            public Builder clearProduceResType() {
                bitField0_ = (bitField0_ & ~0x00000001);
                produceResType_ = 0;
                onChanged();
                return this;
            }

            public boolean hasProduceNum() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public int getProduceNum() {
                return produceNum_;
            }

            public Builder setProduceNum(int value) {
                bitField0_ |= 0x00000002;
                produceNum_ = value;
                onChanged();
                return this;
            }

            public Builder clearProduceNum() {
                bitField0_ = (bitField0_ & ~0x00000002);
                produceNum_ = 0;
                onChanged();
                return this;
            }

            public boolean hasIsMineCarDrive() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public boolean getIsMineCarDrive() {
                return isMineCarDrive_;
            }

            public Builder setIsMineCarDrive(boolean value) {
                bitField0_ |= 0x00000004;
                isMineCarDrive_ = value;
                onChanged();
                return this;
            }

            public Builder clearIsMineCarDrive() {
                bitField0_ = (bitField0_ & ~0x00000004);
                isMineCarDrive_ = false;
                onChanged();
                return this;
            }

            public boolean hasMineResourceNum() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            public int getMineResourceNum() {
                return mineResourceNum_;
            }

            public Builder setMineResourceNum(int value) {
                bitField0_ |= 0x00000008;
                mineResourceNum_ = value;
                onChanged();
                return this;
            }

            public Builder clearMineResourceNum() {
                bitField0_ = (bitField0_ & ~0x00000008);
                mineResourceNum_ = 0;
                onChanged();
                return this;
            }

            public boolean hasProduceMuduls() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            public int getProduceMuduls() {
                return produceMuduls_;
            }

            public Builder setProduceMuduls(int value) {
                bitField0_ |= 0x00000010;
                produceMuduls_ = value;
                onChanged();
                return this;
            }

            public Builder clearProduceMuduls() {
                bitField0_ = (bitField0_ & ~0x00000010);
                produceMuduls_ = 0;
                onChanged();
                return this;
            }

            public boolean hasProduceNumPerhour() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            public int getProduceNumPerhour() {
                return produceNumPerhour_;
            }

            public Builder setProduceNumPerhour(int value) {
                bitField0_ |= 0x00000020;
                produceNumPerhour_ = value;
                onChanged();
                return this;
            }

            public Builder clearProduceNumPerhour() {
                bitField0_ = (bitField0_ & ~0x00000020);
                produceNumPerhour_ = 0;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Mine_Resource_Mes)
        }

        // @@protoc_insertion_point(class_scope:Mine_Resource_Mes)
    }

    // @@protoc_insertion_point(outer_class_scope)
}
