// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Pvp_Battle_End_Req.proto

package com.pkuvr.game_server.proto.clientproto;

public final class Pvp_Battle_End_Request {
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Pvp_Battle_End_Req_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Pvp_Battle_End_Req_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\030Pvp_Battle_End_Req.proto\032\032BI_Battle_Un" +
                        "it_Start.proto\"\240\001\n\022Pvp_Battle_End_Req\022\021\n" +
                        "\tbattleRes\030\001 \002(\005\022\027\n\017battleNormalEnd\030\002 \001(" +
                        "\010\022-\n\rownDamageList\030\003 \003(\0132\026.Battle_Unit_S" +
                        "tart_Mes\022/\n\017otherDamageList\030\004 \003(\0132\026.Batt" +
                        "le_Unit_Start_MesB?\n%com.pkuvr.game_server" +
                        ".proto.clientprotoB\026Pvp_Battle_End_Reque" +
                        "st"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_Pvp_Battle_End_Req_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_Pvp_Battle_End_Req_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_Pvp_Battle_End_Req_descriptor,
                                new String[]{"BattleRes", "BattleNormalEnd", "OwnDamageList", "OtherDamageList",},
                                com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req.class,
                                com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.getDescriptor(),
                        }, assigner);
    }

    private Pvp_Battle_End_Request() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface Pvp_Battle_End_ReqOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required int32 battleRes = 1;
        boolean hasBattleRes();

        int getBattleRes();

        // optional bool battleNormalEnd = 2;
        boolean hasBattleNormalEnd();

        boolean getBattleNormalEnd();

        // repeated .Battle_Unit_Start_Mes ownDamageList = 3;
        java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes>
        getOwnDamageListList();

        com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes getOwnDamageList(int index);

        int getOwnDamageListCount();

        java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder>
        getOwnDamageListOrBuilderList();

        com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder getOwnDamageListOrBuilder(
                int index);

        // repeated .Battle_Unit_Start_Mes otherDamageList = 4;
        java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes>
        getOtherDamageListList();

        com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes getOtherDamageList(int index);

        int getOtherDamageListCount();

        java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder>
        getOtherDamageListOrBuilderList();

        com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder getOtherDamageListOrBuilder(
                int index);
    }

    public static final class Pvp_Battle_End_Req extends
            com.google.protobuf.GeneratedMessage
            implements Pvp_Battle_End_ReqOrBuilder {
        // required int32 battleRes = 1;
        public static final int BATTLERES_FIELD_NUMBER = 1;
        // optional bool battleNormalEnd = 2;
        public static final int BATTLENORMALEND_FIELD_NUMBER = 2;
        // repeated .Battle_Unit_Start_Mes ownDamageList = 3;
        public static final int OWNDAMAGELIST_FIELD_NUMBER = 3;
        // repeated .Battle_Unit_Start_Mes otherDamageList = 4;
        public static final int OTHERDAMAGELIST_FIELD_NUMBER = 4;
        private static final Pvp_Battle_End_Req defaultInstance;
        private static final long serialVersionUID = 0L;

        static {
            defaultInstance = new Pvp_Battle_End_Req(true);
            defaultInstance.initFields();
        }

        private int bitField0_;
        private int battleRes_;
        private boolean battleNormalEnd_;
        private java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes> ownDamageList_;
        private java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes> otherDamageList_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Pvp_Battle_End_Req.newBuilder() to construct.
        private Pvp_Battle_End_Req(Builder builder) {
            super(builder);
        }

        private Pvp_Battle_End_Req(boolean noInit) {
        }

        public static Pvp_Battle_End_Req getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.internal_static_Pvp_Battle_End_Req_descriptor;
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Pvp_Battle_End_Req getDefaultInstanceForType() {
            return defaultInstance;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.internal_static_Pvp_Battle_End_Req_fieldAccessorTable;
        }

        public boolean hasBattleRes() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getBattleRes() {
            return battleRes_;
        }

        public boolean hasBattleNormalEnd() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public boolean getBattleNormalEnd() {
            return battleNormalEnd_;
        }

        public java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes> getOwnDamageListList() {
            return ownDamageList_;
        }

        public java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder>
        getOwnDamageListOrBuilderList() {
            return ownDamageList_;
        }

        public int getOwnDamageListCount() {
            return ownDamageList_.size();
        }

        public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes getOwnDamageList(int index) {
            return ownDamageList_.get(index);
        }

        public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder getOwnDamageListOrBuilder(
                int index) {
            return ownDamageList_.get(index);
        }

        public java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes> getOtherDamageListList() {
            return otherDamageList_;
        }

        public java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder>
        getOtherDamageListOrBuilderList() {
            return otherDamageList_;
        }

        public int getOtherDamageListCount() {
            return otherDamageList_.size();
        }

        public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes getOtherDamageList(int index) {
            return otherDamageList_.get(index);
        }

        public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder getOtherDamageListOrBuilder(
                int index) {
            return otherDamageList_.get(index);
        }

        private void initFields() {
            battleRes_ = 0;
            battleNormalEnd_ = false;
            ownDamageList_ = java.util.Collections.emptyList();
            otherDamageList_ = java.util.Collections.emptyList();
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasBattleRes()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, battleRes_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBool(2, battleNormalEnd_);
            }
            for (int i = 0; i < ownDamageList_.size(); i++) {
                output.writeMessage(3, ownDamageList_.get(i));
            }
            for (int i = 0; i < otherDamageList_.size(); i++) {
                output.writeMessage(4, otherDamageList_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, battleRes_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(2, battleNormalEnd_);
            }
            for (int i = 0; i < ownDamageList_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, ownDamageList_.get(i));
            }
            for (int i = 0; i < otherDamageList_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, otherDamageList_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_ReqOrBuilder {
            private int bitField0_;
            // required int32 battleRes = 1;
            private int battleRes_;
            // optional bool battleNormalEnd = 2;
            private boolean battleNormalEnd_;
            // repeated .Battle_Unit_Start_Mes ownDamageList = 3;
            private java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes> ownDamageList_ =
                    java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilder<
                    com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder> ownDamageListBuilder_;
            // repeated .Battle_Unit_Start_Mes otherDamageList = 4;
            private java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes> otherDamageList_ =
                    java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilder<
                    com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder> otherDamageListBuilder_;

            // Construct using com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.internal_static_Pvp_Battle_End_Req_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.internal_static_Pvp_Battle_End_Req_fieldAccessorTable;
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getOwnDamageListFieldBuilder();
                    getOtherDamageListFieldBuilder();
                }
            }

            public Builder clear() {
                super.clear();
                battleRes_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                battleNormalEnd_ = false;
                bitField0_ = (bitField0_ & ~0x00000002);
                if (ownDamageListBuilder_ == null) {
                    ownDamageList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                } else {
                    ownDamageListBuilder_.clear();
                }
                if (otherDamageListBuilder_ == null) {
                    otherDamageList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000008);
                } else {
                    otherDamageListBuilder_.clear();
                }
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req.getDescriptor();
            }

            public com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req getDefaultInstanceForType() {
                return com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req.getDefaultInstance();
            }

            public com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req build() {
                com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req buildPartial() {
                com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req result = new com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.battleRes_ = battleRes_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.battleNormalEnd_ = battleNormalEnd_;
                if (ownDamageListBuilder_ == null) {
                    if (((bitField0_ & 0x00000004) == 0x00000004)) {
                        ownDamageList_ = java.util.Collections.unmodifiableList(ownDamageList_);
                        bitField0_ = (bitField0_ & ~0x00000004);
                    }
                    result.ownDamageList_ = ownDamageList_;
                } else {
                    result.ownDamageList_ = ownDamageListBuilder_.build();
                }
                if (otherDamageListBuilder_ == null) {
                    if (((bitField0_ & 0x00000008) == 0x00000008)) {
                        otherDamageList_ = java.util.Collections.unmodifiableList(otherDamageList_);
                        bitField0_ = (bitField0_ & ~0x00000008);
                    }
                    result.otherDamageList_ = otherDamageList_;
                } else {
                    result.otherDamageList_ = otherDamageListBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req) {
                    return mergeFrom((com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req other) {
                if (other == com.pkuvr.game_server.proto.clientproto.Pvp_Battle_End_Request.Pvp_Battle_End_Req.getDefaultInstance())
                    return this;
                if (other.hasBattleRes()) {
                    setBattleRes(other.getBattleRes());
                }
                if (other.hasBattleNormalEnd()) {
                    setBattleNormalEnd(other.getBattleNormalEnd());
                }
                if (ownDamageListBuilder_ == null) {
                    if (!other.ownDamageList_.isEmpty()) {
                        if (ownDamageList_.isEmpty()) {
                            ownDamageList_ = other.ownDamageList_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                        } else {
                            ensureOwnDamageListIsMutable();
                            ownDamageList_.addAll(other.ownDamageList_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.ownDamageList_.isEmpty()) {
                        if (ownDamageListBuilder_.isEmpty()) {
                            ownDamageListBuilder_.dispose();
                            ownDamageListBuilder_ = null;
                            ownDamageList_ = other.ownDamageList_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                            ownDamageListBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getOwnDamageListFieldBuilder() : null;
                        } else {
                            ownDamageListBuilder_.addAllMessages(other.ownDamageList_);
                        }
                    }
                }
                if (otherDamageListBuilder_ == null) {
                    if (!other.otherDamageList_.isEmpty()) {
                        if (otherDamageList_.isEmpty()) {
                            otherDamageList_ = other.otherDamageList_;
                            bitField0_ = (bitField0_ & ~0x00000008);
                        } else {
                            ensureOtherDamageListIsMutable();
                            otherDamageList_.addAll(other.otherDamageList_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.otherDamageList_.isEmpty()) {
                        if (otherDamageListBuilder_.isEmpty()) {
                            otherDamageListBuilder_.dispose();
                            otherDamageListBuilder_ = null;
                            otherDamageList_ = other.otherDamageList_;
                            bitField0_ = (bitField0_ & ~0x00000008);
                            otherDamageListBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getOtherDamageListFieldBuilder() : null;
                        } else {
                            otherDamageListBuilder_.addAllMessages(other.otherDamageList_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasBattleRes()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            battleRes_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            battleNormalEnd_ = input.readBool();
                            break;
                        }
                        case 26: {
                            com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder subBuilder = com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.newBuilder();
                            input.readMessage(subBuilder, extensionRegistry);
                            addOwnDamageList(subBuilder.buildPartial());
                            break;
                        }
                        case 34: {
                            com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder subBuilder = com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.newBuilder();
                            input.readMessage(subBuilder, extensionRegistry);
                            addOtherDamageList(subBuilder.buildPartial());
                            break;
                        }
                    }
                }
            }

            public boolean hasBattleRes() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getBattleRes() {
                return battleRes_;
            }

            public Builder setBattleRes(int value) {
                bitField0_ |= 0x00000001;
                battleRes_ = value;
                onChanged();
                return this;
            }

            public Builder clearBattleRes() {
                bitField0_ = (bitField0_ & ~0x00000001);
                battleRes_ = 0;
                onChanged();
                return this;
            }

            public boolean hasBattleNormalEnd() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public boolean getBattleNormalEnd() {
                return battleNormalEnd_;
            }

            public Builder setBattleNormalEnd(boolean value) {
                bitField0_ |= 0x00000002;
                battleNormalEnd_ = value;
                onChanged();
                return this;
            }

            public Builder clearBattleNormalEnd() {
                bitField0_ = (bitField0_ & ~0x00000002);
                battleNormalEnd_ = false;
                onChanged();
                return this;
            }

            private void ensureOwnDamageListIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    ownDamageList_ = new java.util.ArrayList<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes>(ownDamageList_);
                    bitField0_ |= 0x00000004;
                }
            }

            public java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes> getOwnDamageListList() {
                if (ownDamageListBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(ownDamageList_);
                } else {
                    return ownDamageListBuilder_.getMessageList();
                }
            }

            public int getOwnDamageListCount() {
                if (ownDamageListBuilder_ == null) {
                    return ownDamageList_.size();
                } else {
                    return ownDamageListBuilder_.getCount();
                }
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes getOwnDamageList(int index) {
                if (ownDamageListBuilder_ == null) {
                    return ownDamageList_.get(index);
                } else {
                    return ownDamageListBuilder_.getMessage(index);
                }
            }

            public Builder setOwnDamageList(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes value) {
                if (ownDamageListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureOwnDamageListIsMutable();
                    ownDamageList_.set(index, value);
                    onChanged();
                } else {
                    ownDamageListBuilder_.setMessage(index, value);
                }
                return this;
            }

            public Builder setOwnDamageList(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder builderForValue) {
                if (ownDamageListBuilder_ == null) {
                    ensureOwnDamageListIsMutable();
                    ownDamageList_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    ownDamageListBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addOwnDamageList(com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes value) {
                if (ownDamageListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureOwnDamageListIsMutable();
                    ownDamageList_.add(value);
                    onChanged();
                } else {
                    ownDamageListBuilder_.addMessage(value);
                }
                return this;
            }

            public Builder addOwnDamageList(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes value) {
                if (ownDamageListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureOwnDamageListIsMutable();
                    ownDamageList_.add(index, value);
                    onChanged();
                } else {
                    ownDamageListBuilder_.addMessage(index, value);
                }
                return this;
            }

            public Builder addOwnDamageList(
                    com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder builderForValue) {
                if (ownDamageListBuilder_ == null) {
                    ensureOwnDamageListIsMutable();
                    ownDamageList_.add(builderForValue.build());
                    onChanged();
                } else {
                    ownDamageListBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            public Builder addOwnDamageList(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder builderForValue) {
                if (ownDamageListBuilder_ == null) {
                    ensureOwnDamageListIsMutable();
                    ownDamageList_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    ownDamageListBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addAllOwnDamageList(
                    Iterable<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes> values) {
                if (ownDamageListBuilder_ == null) {
                    ensureOwnDamageListIsMutable();
                    super.addAll(values, ownDamageList_);
                    onChanged();
                } else {
                    ownDamageListBuilder_.addAllMessages(values);
                }
                return this;
            }

            public Builder clearOwnDamageList() {
                if (ownDamageListBuilder_ == null) {
                    ownDamageList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                    onChanged();
                } else {
                    ownDamageListBuilder_.clear();
                }
                return this;
            }

            public Builder removeOwnDamageList(int index) {
                if (ownDamageListBuilder_ == null) {
                    ensureOwnDamageListIsMutable();
                    ownDamageList_.remove(index);
                    onChanged();
                } else {
                    ownDamageListBuilder_.remove(index);
                }
                return this;
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder getOwnDamageListBuilder(
                    int index) {
                return getOwnDamageListFieldBuilder().getBuilder(index);
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder getOwnDamageListOrBuilder(
                    int index) {
                if (ownDamageListBuilder_ == null) {
                    return ownDamageList_.get(index);
                } else {
                    return ownDamageListBuilder_.getMessageOrBuilder(index);
                }
            }

            public java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder>
            getOwnDamageListOrBuilderList() {
                if (ownDamageListBuilder_ != null) {
                    return ownDamageListBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(ownDamageList_);
                }
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder addOwnDamageListBuilder() {
                return getOwnDamageListFieldBuilder().addBuilder(
                        com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.getDefaultInstance());
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder addOwnDamageListBuilder(
                    int index) {
                return getOwnDamageListFieldBuilder().addBuilder(
                        index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.getDefaultInstance());
            }

            public java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder>
            getOwnDamageListBuilderList() {
                return getOwnDamageListFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder>
            getOwnDamageListFieldBuilder() {
                if (ownDamageListBuilder_ == null) {
                    ownDamageListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder>(
                            ownDamageList_,
                            ((bitField0_ & 0x00000004) == 0x00000004),
                            getParentForChildren(),
                            isClean());
                    ownDamageList_ = null;
                }
                return ownDamageListBuilder_;
            }

            private void ensureOtherDamageListIsMutable() {
                if (!((bitField0_ & 0x00000008) == 0x00000008)) {
                    otherDamageList_ = new java.util.ArrayList<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes>(otherDamageList_);
                    bitField0_ |= 0x00000008;
                }
            }

            public java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes> getOtherDamageListList() {
                if (otherDamageListBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(otherDamageList_);
                } else {
                    return otherDamageListBuilder_.getMessageList();
                }
            }

            public int getOtherDamageListCount() {
                if (otherDamageListBuilder_ == null) {
                    return otherDamageList_.size();
                } else {
                    return otherDamageListBuilder_.getCount();
                }
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes getOtherDamageList(int index) {
                if (otherDamageListBuilder_ == null) {
                    return otherDamageList_.get(index);
                } else {
                    return otherDamageListBuilder_.getMessage(index);
                }
            }

            public Builder setOtherDamageList(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes value) {
                if (otherDamageListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureOtherDamageListIsMutable();
                    otherDamageList_.set(index, value);
                    onChanged();
                } else {
                    otherDamageListBuilder_.setMessage(index, value);
                }
                return this;
            }

            public Builder setOtherDamageList(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder builderForValue) {
                if (otherDamageListBuilder_ == null) {
                    ensureOtherDamageListIsMutable();
                    otherDamageList_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    otherDamageListBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addOtherDamageList(com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes value) {
                if (otherDamageListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureOtherDamageListIsMutable();
                    otherDamageList_.add(value);
                    onChanged();
                } else {
                    otherDamageListBuilder_.addMessage(value);
                }
                return this;
            }

            public Builder addOtherDamageList(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes value) {
                if (otherDamageListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureOtherDamageListIsMutable();
                    otherDamageList_.add(index, value);
                    onChanged();
                } else {
                    otherDamageListBuilder_.addMessage(index, value);
                }
                return this;
            }

            public Builder addOtherDamageList(
                    com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder builderForValue) {
                if (otherDamageListBuilder_ == null) {
                    ensureOtherDamageListIsMutable();
                    otherDamageList_.add(builderForValue.build());
                    onChanged();
                } else {
                    otherDamageListBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            public Builder addOtherDamageList(
                    int index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder builderForValue) {
                if (otherDamageListBuilder_ == null) {
                    ensureOtherDamageListIsMutable();
                    otherDamageList_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    otherDamageListBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addAllOtherDamageList(
                    Iterable<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes> values) {
                if (otherDamageListBuilder_ == null) {
                    ensureOtherDamageListIsMutable();
                    super.addAll(values, otherDamageList_);
                    onChanged();
                } else {
                    otherDamageListBuilder_.addAllMessages(values);
                }
                return this;
            }

            public Builder clearOtherDamageList() {
                if (otherDamageListBuilder_ == null) {
                    otherDamageList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000008);
                    onChanged();
                } else {
                    otherDamageListBuilder_.clear();
                }
                return this;
            }

            public Builder removeOtherDamageList(int index) {
                if (otherDamageListBuilder_ == null) {
                    ensureOtherDamageListIsMutable();
                    otherDamageList_.remove(index);
                    onChanged();
                } else {
                    otherDamageListBuilder_.remove(index);
                }
                return this;
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder getOtherDamageListBuilder(
                    int index) {
                return getOtherDamageListFieldBuilder().getBuilder(index);
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder getOtherDamageListOrBuilder(
                    int index) {
                if (otherDamageListBuilder_ == null) {
                    return otherDamageList_.get(index);
                } else {
                    return otherDamageListBuilder_.getMessageOrBuilder(index);
                }
            }

            public java.util.List<? extends com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder>
            getOtherDamageListOrBuilderList() {
                if (otherDamageListBuilder_ != null) {
                    return otherDamageListBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(otherDamageList_);
                }
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder addOtherDamageListBuilder() {
                return getOtherDamageListFieldBuilder().addBuilder(
                        com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.getDefaultInstance());
            }

            public com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder addOtherDamageListBuilder(
                    int index) {
                return getOtherDamageListFieldBuilder().addBuilder(
                        index, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.getDefaultInstance());
            }

            public java.util.List<com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder>
            getOtherDamageListBuilderList() {
                return getOtherDamageListFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder>
            getOtherDamageListFieldBuilder() {
                if (otherDamageListBuilder_ == null) {
                    otherDamageListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_Mes.Builder, com.pkuvr.game_server.proto.commons.BI_Battle_Unit_Start.Battle_Unit_Start_MesOrBuilder>(
                            otherDamageList_,
                            ((bitField0_ & 0x00000008) == 0x00000008),
                            getParentForChildren(),
                            isClean());
                    otherDamageList_ = null;
                }
                return otherDamageListBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:Pvp_Battle_End_Req)
        }

        // @@protoc_insertion_point(class_scope:Pvp_Battle_End_Req)
    }

    // @@protoc_insertion_point(outer_class_scope)
}
