// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Pvp_Sync_Attack_Req.proto

package com.pkuvr.game_server.proto.clientproto;

public final class Pvp_Sync_Attack_Request {
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Pvp_Sync_Attack_Req_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Pvp_Sync_Attack_Req_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\031Pvp_Sync_Attack_Req.proto\"\270\001\n\023Pvp_Sync" +
                        "_Attack_Req\022\024\n\014playerRoleId\030\001 \002(\005\022\031\n\021oth" +
                        "erPlayerRoleId\030\002 \002(\005\022\022\n\nattackerId\030\003 \002(\005" +
                        "\022\031\n\021attackerxPosition\030\004 \001(\005\022\031\n\021attackerz" +
                        "Position\030\005 \001(\005\022\022\n\nattackeeId\030\006 \001(\005\022\022\n\ncl" +
                        "ientTime\030\007 \001(\002B@\n%com.pkuvr.game_server.pr" +
                        "oto.clientprotoB\027Pvp_Sync_Attack_Request"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_Pvp_Sync_Attack_Req_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_Pvp_Sync_Attack_Req_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_Pvp_Sync_Attack_Req_descriptor,
                                new String[]{"PlayerRoleId", "OtherPlayerRoleId", "AttackerId", "AttackerxPosition", "AttackerzPosition", "AttackeeId", "ClientTime",},
                                com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req.class,
                                com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    private Pvp_Sync_Attack_Request() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface Pvp_Sync_Attack_ReqOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required int32 playerRoleId = 1;
        boolean hasPlayerRoleId();

        int getPlayerRoleId();

        // required int32 otherPlayerRoleId = 2;
        boolean hasOtherPlayerRoleId();

        int getOtherPlayerRoleId();

        // required int32 attackerId = 3;
        boolean hasAttackerId();

        int getAttackerId();

        // optional int32 attackerxPosition = 4;
        boolean hasAttackerxPosition();

        int getAttackerxPosition();

        // optional int32 attackerzPosition = 5;
        boolean hasAttackerzPosition();

        int getAttackerzPosition();

        // optional int32 attackeeId = 6;
        boolean hasAttackeeId();

        int getAttackeeId();

        // optional float clientTime = 7;
        boolean hasClientTime();

        float getClientTime();
    }

    public static final class Pvp_Sync_Attack_Req extends
            com.google.protobuf.GeneratedMessage
            implements Pvp_Sync_Attack_ReqOrBuilder {
        // required int32 playerRoleId = 1;
        public static final int PLAYERROLEID_FIELD_NUMBER = 1;
        // required int32 otherPlayerRoleId = 2;
        public static final int OTHERPLAYERROLEID_FIELD_NUMBER = 2;
        // required int32 attackerId = 3;
        public static final int ATTACKERID_FIELD_NUMBER = 3;
        // optional int32 attackerxPosition = 4;
        public static final int ATTACKERXPOSITION_FIELD_NUMBER = 4;
        // optional int32 attackerzPosition = 5;
        public static final int ATTACKERZPOSITION_FIELD_NUMBER = 5;
        // optional int32 attackeeId = 6;
        public static final int ATTACKEEID_FIELD_NUMBER = 6;
        // optional float clientTime = 7;
        public static final int CLIENTTIME_FIELD_NUMBER = 7;
        private static final Pvp_Sync_Attack_Req defaultInstance;
        private static final long serialVersionUID = 0L;

        static {
            defaultInstance = new Pvp_Sync_Attack_Req(true);
            defaultInstance.initFields();
        }

        private int bitField0_;
        private int playerRoleId_;
        private int otherPlayerRoleId_;
        private int attackerId_;
        private int attackerxPosition_;
        private int attackerzPosition_;
        private int attackeeId_;
        private float clientTime_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Pvp_Sync_Attack_Req.newBuilder() to construct.
        private Pvp_Sync_Attack_Req(Builder builder) {
            super(builder);
        }
        private Pvp_Sync_Attack_Req(boolean noInit) {
        }

        public static Pvp_Sync_Attack_Req getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.internal_static_Pvp_Sync_Attack_Req_descriptor;
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Pvp_Sync_Attack_Req getDefaultInstanceForType() {
            return defaultInstance;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.internal_static_Pvp_Sync_Attack_Req_fieldAccessorTable;
        }

        public boolean hasPlayerRoleId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getPlayerRoleId() {
            return playerRoleId_;
        }

        public boolean hasOtherPlayerRoleId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public int getOtherPlayerRoleId() {
            return otherPlayerRoleId_;
        }

        public boolean hasAttackerId() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public int getAttackerId() {
            return attackerId_;
        }

        public boolean hasAttackerxPosition() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public int getAttackerxPosition() {
            return attackerxPosition_;
        }

        public boolean hasAttackerzPosition() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        public int getAttackerzPosition() {
            return attackerzPosition_;
        }

        public boolean hasAttackeeId() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }

        public int getAttackeeId() {
            return attackeeId_;
        }

        public boolean hasClientTime() {
            return ((bitField0_ & 0x00000040) == 0x00000040);
        }

        public float getClientTime() {
            return clientTime_;
        }

        private void initFields() {
            playerRoleId_ = 0;
            otherPlayerRoleId_ = 0;
            attackerId_ = 0;
            attackerxPosition_ = 0;
            attackerzPosition_ = 0;
            attackeeId_ = 0;
            clientTime_ = 0F;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasPlayerRoleId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasOtherPlayerRoleId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasAttackerId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, playerRoleId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, otherPlayerRoleId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt32(3, attackerId_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt32(4, attackerxPosition_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeInt32(5, attackerzPosition_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeInt32(6, attackeeId_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                output.writeFloat(7, clientTime_);
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, playerRoleId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, otherPlayerRoleId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, attackerId_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, attackerxPosition_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(5, attackerzPosition_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(6, attackeeId_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(7, clientTime_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_ReqOrBuilder {
            private int bitField0_;
            // required int32 playerRoleId = 1;
            private int playerRoleId_;
            // required int32 otherPlayerRoleId = 2;
            private int otherPlayerRoleId_;
            // required int32 attackerId = 3;
            private int attackerId_;
            // optional int32 attackerxPosition = 4;
            private int attackerxPosition_;
            // optional int32 attackerzPosition = 5;
            private int attackerzPosition_;
            // optional int32 attackeeId = 6;
            private int attackeeId_;
            // optional float clientTime = 7;
            private float clientTime_;

            // Construct using com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.internal_static_Pvp_Sync_Attack_Req_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.internal_static_Pvp_Sync_Attack_Req_fieldAccessorTable;
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                playerRoleId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                otherPlayerRoleId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                attackerId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                attackerxPosition_ = 0;
                bitField0_ = (bitField0_ & ~0x00000008);
                attackerzPosition_ = 0;
                bitField0_ = (bitField0_ & ~0x00000010);
                attackeeId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000020);
                clientTime_ = 0F;
                bitField0_ = (bitField0_ & ~0x00000040);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req.getDescriptor();
            }

            public com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req getDefaultInstanceForType() {
                return com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req.getDefaultInstance();
            }

            public com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req build() {
                com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req buildPartial() {
                com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req result = new com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.playerRoleId_ = playerRoleId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.otherPlayerRoleId_ = otherPlayerRoleId_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.attackerId_ = attackerId_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.attackerxPosition_ = attackerxPosition_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.attackerzPosition_ = attackerzPosition_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.attackeeId_ = attackeeId_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000040;
                }
                result.clientTime_ = clientTime_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req) {
                    return mergeFrom((com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req other) {
                if (other == com.pkuvr.game_server.proto.clientproto.Pvp_Sync_Attack_Request.Pvp_Sync_Attack_Req.getDefaultInstance())
                    return this;
                if (other.hasPlayerRoleId()) {
                    setPlayerRoleId(other.getPlayerRoleId());
                }
                if (other.hasOtherPlayerRoleId()) {
                    setOtherPlayerRoleId(other.getOtherPlayerRoleId());
                }
                if (other.hasAttackerId()) {
                    setAttackerId(other.getAttackerId());
                }
                if (other.hasAttackerxPosition()) {
                    setAttackerxPosition(other.getAttackerxPosition());
                }
                if (other.hasAttackerzPosition()) {
                    setAttackerzPosition(other.getAttackerzPosition());
                }
                if (other.hasAttackeeId()) {
                    setAttackeeId(other.getAttackeeId());
                }
                if (other.hasClientTime()) {
                    setClientTime(other.getClientTime());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasPlayerRoleId()) {

                    return false;
                }
                if (!hasOtherPlayerRoleId()) {

                    return false;
                }
                if (!hasAttackerId()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            playerRoleId_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            otherPlayerRoleId_ = input.readInt32();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            attackerId_ = input.readInt32();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            attackerxPosition_ = input.readInt32();
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000010;
                            attackerzPosition_ = input.readInt32();
                            break;
                        }
                        case 48: {
                            bitField0_ |= 0x00000020;
                            attackeeId_ = input.readInt32();
                            break;
                        }
                        case 61: {
                            bitField0_ |= 0x00000040;
                            clientTime_ = input.readFloat();
                            break;
                        }
                    }
                }
            }

            public boolean hasPlayerRoleId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getPlayerRoleId() {
                return playerRoleId_;
            }

            public Builder setPlayerRoleId(int value) {
                bitField0_ |= 0x00000001;
                playerRoleId_ = value;
                onChanged();
                return this;
            }

            public Builder clearPlayerRoleId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                playerRoleId_ = 0;
                onChanged();
                return this;
            }

            public boolean hasOtherPlayerRoleId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public int getOtherPlayerRoleId() {
                return otherPlayerRoleId_;
            }

            public Builder setOtherPlayerRoleId(int value) {
                bitField0_ |= 0x00000002;
                otherPlayerRoleId_ = value;
                onChanged();
                return this;
            }

            public Builder clearOtherPlayerRoleId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                otherPlayerRoleId_ = 0;
                onChanged();
                return this;
            }

            public boolean hasAttackerId() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public int getAttackerId() {
                return attackerId_;
            }

            public Builder setAttackerId(int value) {
                bitField0_ |= 0x00000004;
                attackerId_ = value;
                onChanged();
                return this;
            }

            public Builder clearAttackerId() {
                bitField0_ = (bitField0_ & ~0x00000004);
                attackerId_ = 0;
                onChanged();
                return this;
            }

            public boolean hasAttackerxPosition() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            public int getAttackerxPosition() {
                return attackerxPosition_;
            }

            public Builder setAttackerxPosition(int value) {
                bitField0_ |= 0x00000008;
                attackerxPosition_ = value;
                onChanged();
                return this;
            }

            public Builder clearAttackerxPosition() {
                bitField0_ = (bitField0_ & ~0x00000008);
                attackerxPosition_ = 0;
                onChanged();
                return this;
            }

            public boolean hasAttackerzPosition() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            public int getAttackerzPosition() {
                return attackerzPosition_;
            }

            public Builder setAttackerzPosition(int value) {
                bitField0_ |= 0x00000010;
                attackerzPosition_ = value;
                onChanged();
                return this;
            }

            public Builder clearAttackerzPosition() {
                bitField0_ = (bitField0_ & ~0x00000010);
                attackerzPosition_ = 0;
                onChanged();
                return this;
            }

            public boolean hasAttackeeId() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            public int getAttackeeId() {
                return attackeeId_;
            }

            public Builder setAttackeeId(int value) {
                bitField0_ |= 0x00000020;
                attackeeId_ = value;
                onChanged();
                return this;
            }

            public Builder clearAttackeeId() {
                bitField0_ = (bitField0_ & ~0x00000020);
                attackeeId_ = 0;
                onChanged();
                return this;
            }

            public boolean hasClientTime() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }

            public float getClientTime() {
                return clientTime_;
            }

            public Builder setClientTime(float value) {
                bitField0_ |= 0x00000040;
                clientTime_ = value;
                onChanged();
                return this;
            }

            public Builder clearClientTime() {
                bitField0_ = (bitField0_ & ~0x00000040);
                clientTime_ = 0F;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Pvp_Sync_Attack_Req)
        }

        // @@protoc_insertion_point(class_scope:Pvp_Sync_Attack_Req)
    }

    // @@protoc_insertion_point(outer_class_scope)
}
