package com.pkuvr.game_server.dao;

import com.pkuvr.game_server.domain.Defensezonebattlelog;
import com.pkuvr.game_server.domain.DefensezonebattlelogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DefensezonebattlelogMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DefenseZoneBattleLog
     *
     * @mbggenerated Fri Nov 27 15:38:18 CST 2015
     */
    int countByExample(DefensezonebattlelogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DefenseZoneBattleLog
     *
     * @mbggenerated Fri Nov 27 15:38:18 CST 2015
     */
    int deleteByExample(DefensezonebattlelogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DefenseZoneBattleLog
     *
     * @mbggenerated Fri Nov 27 15:38:18 CST 2015
     */
    int deleteByPrimaryKey(Long battlelogid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DefenseZoneBattleLog
     *
     * @mbggenerated Fri Nov 27 15:38:18 CST 2015
     */
    int insert(Defensezonebattlelog record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DefenseZoneBattleLog
     *
     * @mbggenerated Fri Nov 27 15:38:18 CST 2015
     */
    int insertSelective(Defensezonebattlelog record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DefenseZoneBattleLog
     *
     * @mbggenerated Fri Nov 27 15:38:18 CST 2015
     */
    List<Defensezonebattlelog> selectByExample(
            DefensezonebattlelogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DefenseZoneBattleLog
     *
     * @mbggenerated Fri Nov 27 15:38:18 CST 2015
     */
    Defensezonebattlelog selectByPrimaryKey(Long battlelogid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DefenseZoneBattleLog
     *
     * @mbggenerated Fri Nov 27 15:38:18 CST 2015
     */
    int updateByExampleSelective(@Param("record") Defensezonebattlelog record,
                                 @Param("example") DefensezonebattlelogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DefenseZoneBattleLog
     *
     * @mbggenerated Fri Nov 27 15:38:18 CST 2015
     */
    int updateByExample(@Param("record") Defensezonebattlelog record,
                        @Param("example") DefensezonebattlelogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DefenseZoneBattleLog
     *
     * @mbggenerated Fri Nov 27 15:38:18 CST 2015
     */
    int updateByPrimaryKeySelective(Defensezonebattlelog record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DefenseZoneBattleLog
     *
     * @mbggenerated Fri Nov 27 15:38:18 CST 2015
     */
    int updateByPrimaryKey(Defensezonebattlelog record);
}