package com.pkuvr.game_server.dao;

import com.pkuvr.game_server.domain.Dichonorreward;
import com.pkuvr.game_server.domain.DichonorrewardExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DichonorrewardMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicHonorReward
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    int countByExample(DichonorrewardExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicHonorReward
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    int deleteByExample(DichonorrewardExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicHonorReward
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    int deleteByPrimaryKey(Integer rewardid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicHonorReward
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    int insert(Dichonorreward record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicHonorReward
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    int insertSelective(Dichonorreward record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicHonorReward
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    List<Dichonorreward> selectByExample(DichonorrewardExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicHonorReward
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    Dichonorreward selectByPrimaryKey(Integer rewardid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicHonorReward
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    int updateByExampleSelective(@Param("record") Dichonorreward record,
                                 @Param("example") DichonorrewardExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicHonorReward
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    int updateByExample(@Param("record") Dichonorreward record,
                        @Param("example") DichonorrewardExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicHonorReward
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    int updateByPrimaryKeySelective(Dichonorreward record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicHonorReward
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    int updateByPrimaryKey(Dichonorreward record);
}