package com.pkuvr.game_server.dao;

import com.pkuvr.game_server.domain.Dicminebuilding;
import com.pkuvr.game_server.domain.DicminebuildingExample;
import com.pkuvr.game_server.domain.DicminebuildingKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DicminebuildingMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicMineBuilding
     *
     * @mbggenerated Wed Dec 31 15:53:56 CST 2014
     */
    int countByExample(DicminebuildingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicMineBuilding
     *
     * @mbggenerated Wed Dec 31 15:53:56 CST 2014
     */
    int deleteByExample(DicminebuildingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicMineBuilding
     *
     * @mbggenerated Wed Dec 31 15:53:56 CST 2014
     */
    int deleteByPrimaryKey(DicminebuildingKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicMineBuilding
     *
     * @mbggenerated Wed Dec 31 15:53:56 CST 2014
     */
    int insert(Dicminebuilding record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicMineBuilding
     *
     * @mbggenerated Wed Dec 31 15:53:56 CST 2014
     */
    int insertSelective(Dicminebuilding record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicMineBuilding
     *
     * @mbggenerated Wed Dec 31 15:53:56 CST 2014
     */
    List<Dicminebuilding> selectByExample(DicminebuildingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicMineBuilding
     *
     * @mbggenerated Wed Dec 31 15:53:56 CST 2014
     */
    Dicminebuilding selectByPrimaryKey(DicminebuildingKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicMineBuilding
     *
     * @mbggenerated Wed Dec 31 15:53:56 CST 2014
     */
    int updateByExampleSelective(@Param("record") Dicminebuilding record,
                                 @Param("example") DicminebuildingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicMineBuilding
     *
     * @mbggenerated Wed Dec 31 15:53:56 CST 2014
     */
    int updateByExample(@Param("record") Dicminebuilding record,
                        @Param("example") DicminebuildingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicMineBuilding
     *
     * @mbggenerated Wed Dec 31 15:53:56 CST 2014
     */
    int updateByPrimaryKeySelective(Dicminebuilding record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicMineBuilding
     *
     * @mbggenerated Wed Dec 31 15:53:56 CST 2014
     */
    int updateByPrimaryKey(Dicminebuilding record);
}