package com.pkuvr.game_server.dao;

import com.pkuvr.game_server.domain.Dicresourceminetype;
import com.pkuvr.game_server.domain.DicresourceminetypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DicresourceminetypeMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicResourceMineType
     *
     * @mbggenerated Mon Jan 05 11:16:44 CST 2015
     */
    int countByExample(DicresourceminetypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicResourceMineType
     *
     * @mbggenerated Mon Jan 05 11:16:44 CST 2015
     */
    int deleteByExample(DicresourceminetypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicResourceMineType
     *
     * @mbggenerated Mon Jan 05 11:16:44 CST 2015
     */
    int deleteByPrimaryKey(Integer resminetypeid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicResourceMineType
     *
     * @mbggenerated Mon Jan 05 11:16:44 CST 2015
     */
    int insert(Dicresourceminetype record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicResourceMineType
     *
     * @mbggenerated Mon Jan 05 11:16:44 CST 2015
     */
    int insertSelective(Dicresourceminetype record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicResourceMineType
     *
     * @mbggenerated Mon Jan 05 11:16:44 CST 2015
     */
    List<Dicresourceminetype> selectByExample(DicresourceminetypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicResourceMineType
     *
     * @mbggenerated Mon Jan 05 11:16:44 CST 2015
     */
    Dicresourceminetype selectByPrimaryKey(Integer resminetypeid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicResourceMineType
     *
     * @mbggenerated Mon Jan 05 11:16:44 CST 2015
     */
    int updateByExampleSelective(@Param("record") Dicresourceminetype record,
                                 @Param("example") DicresourceminetypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicResourceMineType
     *
     * @mbggenerated Mon Jan 05 11:16:44 CST 2015
     */
    int updateByExample(@Param("record") Dicresourceminetype record,
                        @Param("example") DicresourceminetypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicResourceMineType
     *
     * @mbggenerated Mon Jan 05 11:16:44 CST 2015
     */
    int updateByPrimaryKeySelective(Dicresourceminetype record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DicResourceMineType
     *
     * @mbggenerated Mon Jan 05 11:16:44 CST 2015
     */
    int updateByPrimaryKey(Dicresourceminetype record);
}