package com.pkuvr.game_server.dao;

import com.pkuvr.game_server.domain.Playerresourceminecollect;
import com.pkuvr.game_server.domain.PlayerresourceminecollectExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PlayerresourceminecollectMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PlayerResourceMineCollect
     *
     * @mbggenerated Wed Apr 27 11:08:54 CST 2016
     */
    int countByExample(PlayerresourceminecollectExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PlayerResourceMineCollect
     *
     * @mbggenerated Wed Apr 27 11:08:54 CST 2016
     */
    int deleteByExample(PlayerresourceminecollectExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PlayerResourceMineCollect
     *
     * @mbggenerated Wed Apr 27 11:08:54 CST 2016
     */
    int deleteByPrimaryKey(Long npcresmineid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PlayerResourceMineCollect
     *
     * @mbggenerated Wed Apr 27 11:08:54 CST 2016
     */
    int insert(Playerresourceminecollect record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PlayerResourceMineCollect
     *
     * @mbggenerated Wed Apr 27 11:08:54 CST 2016
     */
    int insertSelective(Playerresourceminecollect record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PlayerResourceMineCollect
     *
     * @mbggenerated Wed Apr 27 11:08:54 CST 2016
     */
    List<Playerresourceminecollect> selectByExample(
            PlayerresourceminecollectExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PlayerResourceMineCollect
     *
     * @mbggenerated Wed Apr 27 11:08:54 CST 2016
     */
    Playerresourceminecollect selectByPrimaryKey(Long npcresmineid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PlayerResourceMineCollect
     *
     * @mbggenerated Wed Apr 27 11:08:54 CST 2016
     */
    int updateByExampleSelective(
            @Param("record") Playerresourceminecollect record,
            @Param("example") PlayerresourceminecollectExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PlayerResourceMineCollect
     *
     * @mbggenerated Wed Apr 27 11:08:54 CST 2016
     */
    int updateByExample(@Param("record") Playerresourceminecollect record,
                        @Param("example") PlayerresourceminecollectExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PlayerResourceMineCollect
     *
     * @mbggenerated Wed Apr 27 11:08:54 CST 2016
     */
    int updateByPrimaryKeySelective(Playerresourceminecollect record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PlayerResourceMineCollect
     *
     * @mbggenerated Wed Apr 27 11:08:54 CST 2016
     */
    int updateByPrimaryKey(Playerresourceminecollect record);
}