package com.pkuvr.game_server.dao;

import com.pkuvr.game_server.domain.Playermineleftresource;
import com.pkuvr.game_server.domain.PlayermineleftresourceExample;
import com.pkuvr.game_server.domain.PlayermineleftresourceKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PlayermineleftresourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PlayerMineLeftResource
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int countByExample(PlayermineleftresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PlayerMineLeftResource
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int deleteByExample(PlayermineleftresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PlayerMineLeftResource
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int deleteByPrimaryKey(PlayermineleftresourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PlayerMineLeftResource
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int insert(Playermineleftresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PlayerMineLeftResource
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int insertSelective(Playermineleftresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PlayerMineLeftResource
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    List<Playermineleftresource> selectByExample(PlayermineleftresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PlayerMineLeftResource
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    Playermineleftresource selectByPrimaryKey(PlayermineleftresourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PlayerMineLeftResource
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") Playermineleftresource record, @Param("example") PlayermineleftresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PlayerMineLeftResource
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int updateByExample(@Param("record") Playermineleftresource record, @Param("example") PlayermineleftresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PlayerMineLeftResource
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int updateByPrimaryKeySelective(Playermineleftresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PlayerMineLeftResource
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int updateByPrimaryKey(Playermineleftresource record);
}