package com.pkuvr.game_server.dao;

import com.pkuvr.game_server.domain.Realtimepvptokenhistory;
import com.pkuvr.game_server.domain.RealtimepvptokenhistoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RealtimepvptokenhistoryMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpTokenHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int countByExample(RealtimepvptokenhistoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpTokenHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int deleteByExample(RealtimepvptokenhistoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpTokenHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int deleteByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpTokenHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int insert(Realtimepvptokenhistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpTokenHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int insertSelective(Realtimepvptokenhistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpTokenHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    List<Realtimepvptokenhistory> selectByExample(
            RealtimepvptokenhistoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpTokenHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    Realtimepvptokenhistory selectByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpTokenHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int updateByExampleSelective(
            @Param("record") Realtimepvptokenhistory record,
            @Param("example") RealtimepvptokenhistoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpTokenHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int updateByExample(@Param("record") Realtimepvptokenhistory record,
                        @Param("example") RealtimepvptokenhistoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpTokenHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int updateByPrimaryKeySelective(Realtimepvptokenhistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpTokenHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int updateByPrimaryKey(Realtimepvptokenhistory record);
}