package com.pkuvr.game_server.dao;

import com.pkuvr.game_server.domain.Realtimepvpnpchistory;
import com.pkuvr.game_server.domain.RealtimepvpnpchistoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RealtimepvpnpchistoryMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpNpcHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int countByExample(RealtimepvpnpchistoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpNpcHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int deleteByExample(RealtimepvpnpchistoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpNpcHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int deleteByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpNpcHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int insert(Realtimepvpnpchistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpNpcHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int insertSelective(Realtimepvpnpchistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpNpcHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    List<Realtimepvpnpchistory> selectByExample(
            RealtimepvpnpchistoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpNpcHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    Realtimepvpnpchistory selectByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpNpcHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") Realtimepvpnpchistory record,
                                 @Param("example") RealtimepvpnpchistoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpNpcHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int updateByExample(@Param("record") Realtimepvpnpchistory record,
                        @Param("example") RealtimepvpnpchistoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpNpcHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int updateByPrimaryKeySelective(Realtimepvpnpchistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RealTimePvpNpcHistory
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    int updateByPrimaryKey(Realtimepvpnpchistory record);
}