package com.pkuvr.game_server.dao;

import com.pkuvr.game_server.domain.Refreshresourcemine;
import com.pkuvr.game_server.domain.RefreshresourcemineExample;
import com.pkuvr.game_server.domain.RefreshresourcemineKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RefreshresourcemineMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RefreshResourceMine
     *
     * @mbggenerated Wed Aug 26 18:43:35 CST 2015
     */
    int countByExample(RefreshresourcemineExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RefreshResourceMine
     *
     * @mbggenerated Wed Aug 26 18:43:35 CST 2015
     */
    int deleteByExample(RefreshresourcemineExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RefreshResourceMine
     *
     * @mbggenerated Wed Aug 26 18:43:35 CST 2015
     */
    int deleteByPrimaryKey(RefreshresourcemineKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RefreshResourceMine
     *
     * @mbggenerated Wed Aug 26 18:43:35 CST 2015
     */
    int insert(Refreshresourcemine record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RefreshResourceMine
     *
     * @mbggenerated Wed Aug 26 18:43:35 CST 2015
     */
    int insertSelective(Refreshresourcemine record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RefreshResourceMine
     *
     * @mbggenerated Wed Aug 26 18:43:35 CST 2015
     */
    List<Refreshresourcemine> selectByExample(RefreshresourcemineExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RefreshResourceMine
     *
     * @mbggenerated Wed Aug 26 18:43:35 CST 2015
     */
    Refreshresourcemine selectByPrimaryKey(RefreshresourcemineKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RefreshResourceMine
     *
     * @mbggenerated Wed Aug 26 18:43:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") Refreshresourcemine record,
                                 @Param("example") RefreshresourcemineExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RefreshResourceMine
     *
     * @mbggenerated Wed Aug 26 18:43:35 CST 2015
     */
    int updateByExample(@Param("record") Refreshresourcemine record,
                        @Param("example") RefreshresourcemineExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RefreshResourceMine
     *
     * @mbggenerated Wed Aug 26 18:43:35 CST 2015
     */
    int updateByPrimaryKeySelective(Refreshresourcemine record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table RefreshResourceMine
     *
     * @mbggenerated Wed Aug 26 18:43:35 CST 2015
     */
    int updateByPrimaryKey(Refreshresourcemine record);
}