package com.pkuvr.manage_server.dao;

import com.pkuvr.manage_server.domain.ExchangeCodeCreate;
import com.pkuvr.manage_server.domain.ExchangeCodeCreateExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ExchangeCodeCreateMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Exchange_Code_Create
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    int countByExample(ExchangeCodeCreateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Exchange_Code_Create
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    int deleteByExample(ExchangeCodeCreateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Exchange_Code_Create
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Exchange_Code_Create
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    int insert(ExchangeCodeCreate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Exchange_Code_Create
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    int insertSelective(ExchangeCodeCreate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Exchange_Code_Create
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    List<ExchangeCodeCreate> selectByExample(ExchangeCodeCreateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Exchange_Code_Create
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    ExchangeCodeCreate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Exchange_Code_Create
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    int updateByExampleSelective(@Param("record") ExchangeCodeCreate record,
                                 @Param("example") ExchangeCodeCreateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Exchange_Code_Create
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    int updateByExample(@Param("record") ExchangeCodeCreate record,
                        @Param("example") ExchangeCodeCreateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Exchange_Code_Create
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    int updateByPrimaryKeySelective(ExchangeCodeCreate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Exchange_Code_Create
     *
     * @mbggenerated Fri May 15 13:07:45 CST 2015
     */
    int updateByPrimaryKey(ExchangeCodeCreate record);
}