package com.pkuvr.game_server.domain;

public class Dichonorreward {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DicHonorReward.rewardId
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    private Integer rewardid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DicHonorReward.beginValue
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    private Integer beginvalue;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DicHonorReward.endValue
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    private Integer endvalue;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DicHonorReward.rewardHonor
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    private Integer rewardhonor;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DicHonorReward.subHonor
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    private Integer subhonor;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DicHonorReward.beginHonor
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    private Integer beginhonor;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DicHonorReward.endHonor
     *
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    private Integer endhonor;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DicHonorReward.rewardId
     *
     * @return the value of DicHonorReward.rewardId
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    public Integer getRewardid() {
        return rewardid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DicHonorReward.rewardId
     *
     * @param rewardid the value for DicHonorReward.rewardId
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    public void setRewardid(Integer rewardid) {
        this.rewardid = rewardid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DicHonorReward.beginValue
     *
     * @return the value of DicHonorReward.beginValue
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    public Integer getBeginvalue() {
        return beginvalue;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DicHonorReward.beginValue
     *
     * @param beginvalue the value for DicHonorReward.beginValue
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    public void setBeginvalue(Integer beginvalue) {
        this.beginvalue = beginvalue;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DicHonorReward.endValue
     *
     * @return the value of DicHonorReward.endValue
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    public Integer getEndvalue() {
        return endvalue;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DicHonorReward.endValue
     *
     * @param endvalue the value for DicHonorReward.endValue
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    public void setEndvalue(Integer endvalue) {
        this.endvalue = endvalue;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DicHonorReward.rewardHonor
     *
     * @return the value of DicHonorReward.rewardHonor
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    public Integer getRewardhonor() {
        return rewardhonor;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DicHonorReward.rewardHonor
     *
     * @param rewardhonor the value for DicHonorReward.rewardHonor
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    public void setRewardhonor(Integer rewardhonor) {
        this.rewardhonor = rewardhonor;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DicHonorReward.subHonor
     *
     * @return the value of DicHonorReward.subHonor
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    public Integer getSubhonor() {
        return subhonor;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DicHonorReward.subHonor
     *
     * @param subhonor the value for DicHonorReward.subHonor
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    public void setSubhonor(Integer subhonor) {
        this.subhonor = subhonor;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DicHonorReward.beginHonor
     *
     * @return the value of DicHonorReward.beginHonor
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    public Integer getBeginhonor() {
        return beginhonor;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DicHonorReward.beginHonor
     *
     * @param beginhonor the value for DicHonorReward.beginHonor
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    public void setBeginhonor(Integer beginhonor) {
        this.beginhonor = beginhonor;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DicHonorReward.endHonor
     *
     * @return the value of DicHonorReward.endHonor
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    public Integer getEndhonor() {
        return endhonor;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DicHonorReward.endHonor
     *
     * @param endhonor the value for DicHonorReward.endHonor
     * @mbggenerated Tue Jan 06 15:42:50 CST 2015
     */
    public void setEndhonor(Integer endhonor) {
        this.endhonor = endhonor;
    }
}