package com.pkuvr.game_server.domain;

import java.util.ArrayList;
import java.util.List;

public class DicresminerelaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public DicresminerelaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andResminenumIsNull() {
            addCriterion("resMineNum is null");
            return (Criteria) this;
        }

        public Criteria andResminenumIsNotNull() {
            addCriterion("resMineNum is not null");
            return (Criteria) this;
        }

        public Criteria andResminenumEqualTo(Integer value) {
            addCriterion("resMineNum =", value, "resminenum");
            return (Criteria) this;
        }

        public Criteria andResminenumNotEqualTo(Integer value) {
            addCriterion("resMineNum <>", value, "resminenum");
            return (Criteria) this;
        }

        public Criteria andResminenumGreaterThan(Integer value) {
            addCriterion("resMineNum >", value, "resminenum");
            return (Criteria) this;
        }

        public Criteria andResminenumGreaterThanOrEqualTo(Integer value) {
            addCriterion("resMineNum >=", value, "resminenum");
            return (Criteria) this;
        }

        public Criteria andResminenumLessThan(Integer value) {
            addCriterion("resMineNum <", value, "resminenum");
            return (Criteria) this;
        }

        public Criteria andResminenumLessThanOrEqualTo(Integer value) {
            addCriterion("resMineNum <=", value, "resminenum");
            return (Criteria) this;
        }

        public Criteria andResminenumIn(List<Integer> values) {
            addCriterion("resMineNum in", values, "resminenum");
            return (Criteria) this;
        }

        public Criteria andResminenumNotIn(List<Integer> values) {
            addCriterion("resMineNum not in", values, "resminenum");
            return (Criteria) this;
        }

        public Criteria andResminenumBetween(Integer value1, Integer value2) {
            addCriterion("resMineNum between", value1, value2, "resminenum");
            return (Criteria) this;
        }

        public Criteria andResminenumNotBetween(Integer value1, Integer value2) {
            addCriterion("resMineNum not between", value1, value2, "resminenum");
            return (Criteria) this;
        }

        public Criteria andResproducemodulusIsNull() {
            addCriterion("resProduceModulus is null");
            return (Criteria) this;
        }

        public Criteria andResproducemodulusIsNotNull() {
            addCriterion("resProduceModulus is not null");
            return (Criteria) this;
        }

        public Criteria andResproducemodulusEqualTo(Float value) {
            addCriterion("resProduceModulus =", value, "resproducemodulus");
            return (Criteria) this;
        }

        public Criteria andResproducemodulusNotEqualTo(Float value) {
            addCriterion("resProduceModulus <>", value, "resproducemodulus");
            return (Criteria) this;
        }

        public Criteria andResproducemodulusGreaterThan(Float value) {
            addCriterion("resProduceModulus >", value, "resproducemodulus");
            return (Criteria) this;
        }

        public Criteria andResproducemodulusGreaterThanOrEqualTo(Float value) {
            addCriterion("resProduceModulus >=", value, "resproducemodulus");
            return (Criteria) this;
        }

        public Criteria andResproducemodulusLessThan(Float value) {
            addCriterion("resProduceModulus <", value, "resproducemodulus");
            return (Criteria) this;
        }

        public Criteria andResproducemodulusLessThanOrEqualTo(Float value) {
            addCriterion("resProduceModulus <=", value, "resproducemodulus");
            return (Criteria) this;
        }

        public Criteria andResproducemodulusIn(List<Float> values) {
            addCriterion("resProduceModulus in", values, "resproducemodulus");
            return (Criteria) this;
        }

        public Criteria andResproducemodulusNotIn(List<Float> values) {
            addCriterion("resProduceModulus not in", values, "resproducemodulus");
            return (Criteria) this;
        }

        public Criteria andResproducemodulusBetween(Float value1, Float value2) {
            addCriterion("resProduceModulus between", value1, value2, "resproducemodulus");
            return (Criteria) this;
        }

        public Criteria andResproducemodulusNotBetween(Float value1, Float value2) {
            addCriterion("resProduceModulus not between", value1, value2, "resproducemodulus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DicResMineRela
     *
     * @mbggenerated do_not_delete_during_merge Thu May 19 12:37:02 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DicResMineRela
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}