package com.pkuvr.game_server.domain;

import java.util.ArrayList;
import java.util.List;

public class MineattackhistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    public MineattackhistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNpcresmineidIsNull() {
            addCriterion("NpcResMineID is null");
            return (Criteria) this;
        }

        public Criteria andNpcresmineidIsNotNull() {
            addCriterion("NpcResMineID is not null");
            return (Criteria) this;
        }

        public Criteria andNpcresmineidEqualTo(Long value) {
            addCriterion("NpcResMineID =", value, "npcresmineid");
            return (Criteria) this;
        }

        public Criteria andNpcresmineidNotEqualTo(Long value) {
            addCriterion("NpcResMineID <>", value, "npcresmineid");
            return (Criteria) this;
        }

        public Criteria andNpcresmineidGreaterThan(Long value) {
            addCriterion("NpcResMineID >", value, "npcresmineid");
            return (Criteria) this;
        }

        public Criteria andNpcresmineidGreaterThanOrEqualTo(Long value) {
            addCriterion("NpcResMineID >=", value, "npcresmineid");
            return (Criteria) this;
        }

        public Criteria andNpcresmineidLessThan(Long value) {
            addCriterion("NpcResMineID <", value, "npcresmineid");
            return (Criteria) this;
        }

        public Criteria andNpcresmineidLessThanOrEqualTo(Long value) {
            addCriterion("NpcResMineID <=", value, "npcresmineid");
            return (Criteria) this;
        }

        public Criteria andNpcresmineidIn(List<Long> values) {
            addCriterion("NpcResMineID in", values, "npcresmineid");
            return (Criteria) this;
        }

        public Criteria andNpcresmineidNotIn(List<Long> values) {
            addCriterion("NpcResMineID not in", values, "npcresmineid");
            return (Criteria) this;
        }

        public Criteria andNpcresmineidBetween(Long value1, Long value2) {
            addCriterion("NpcResMineID between", value1, value2, "npcresmineid");
            return (Criteria) this;
        }

        public Criteria andNpcresmineidNotBetween(Long value1, Long value2) {
            addCriterion("NpcResMineID not between", value1, value2, "npcresmineid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidIsNull() {
            addCriterion("attackerRoleID is null");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidIsNotNull() {
            addCriterion("attackerRoleID is not null");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidEqualTo(Integer value) {
            addCriterion("attackerRoleID =", value, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidNotEqualTo(Integer value) {
            addCriterion("attackerRoleID <>", value, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidGreaterThan(Integer value) {
            addCriterion("attackerRoleID >", value, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidGreaterThanOrEqualTo(Integer value) {
            addCriterion("attackerRoleID >=", value, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidLessThan(Integer value) {
            addCriterion("attackerRoleID <", value, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidLessThanOrEqualTo(Integer value) {
            addCriterion("attackerRoleID <=", value, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidIn(List<Integer> values) {
            addCriterion("attackerRoleID in", values, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidNotIn(List<Integer> values) {
            addCriterion("attackerRoleID not in", values, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidBetween(Integer value1, Integer value2) {
            addCriterion("attackerRoleID between", value1, value2, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidNotBetween(Integer value1, Integer value2) {
            addCriterion("attackerRoleID not between", value1, value2, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttacktimesIsNull() {
            addCriterion("attackTimes is null");
            return (Criteria) this;
        }

        public Criteria andAttacktimesIsNotNull() {
            addCriterion("attackTimes is not null");
            return (Criteria) this;
        }

        public Criteria andAttacktimesEqualTo(Short value) {
            addCriterion("attackTimes =", value, "attacktimes");
            return (Criteria) this;
        }

        public Criteria andAttacktimesNotEqualTo(Short value) {
            addCriterion("attackTimes <>", value, "attacktimes");
            return (Criteria) this;
        }

        public Criteria andAttacktimesGreaterThan(Short value) {
            addCriterion("attackTimes >", value, "attacktimes");
            return (Criteria) this;
        }

        public Criteria andAttacktimesGreaterThanOrEqualTo(Short value) {
            addCriterion("attackTimes >=", value, "attacktimes");
            return (Criteria) this;
        }

        public Criteria andAttacktimesLessThan(Short value) {
            addCriterion("attackTimes <", value, "attacktimes");
            return (Criteria) this;
        }

        public Criteria andAttacktimesLessThanOrEqualTo(Short value) {
            addCriterion("attackTimes <=", value, "attacktimes");
            return (Criteria) this;
        }

        public Criteria andAttacktimesIn(List<Short> values) {
            addCriterion("attackTimes in", values, "attacktimes");
            return (Criteria) this;
        }

        public Criteria andAttacktimesNotIn(List<Short> values) {
            addCriterion("attackTimes not in", values, "attacktimes");
            return (Criteria) this;
        }

        public Criteria andAttacktimesBetween(Short value1, Short value2) {
            addCriterion("attackTimes between", value1, value2, "attacktimes");
            return (Criteria) this;
        }

        public Criteria andAttacktimesNotBetween(Short value1, Short value2) {
            addCriterion("attackTimes not between", value1, value2, "attacktimes");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MineAttackHistory
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 19 17:02:01 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MineAttackHistory
     *
     * @mbggenerated Fri Jun 19 17:02:01 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}