package com.pkuvr.game_server.domain;

public class PlayerresourcemineKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PlayerResourceMine.roleID
     *
     * @mbggenerated Wed Jan 28 10:55:47 CST 2015
     */
    private Integer roleid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PlayerResourceMine.NpcResMineID
     *
     * @mbggenerated Wed Jan 28 10:55:47 CST 2015
     */
    private Long npcresmineid;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PlayerResourceMine.roleID
     *
     * @return the value of PlayerResourceMine.roleID
     * @mbggenerated Wed Jan 28 10:55:47 CST 2015
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PlayerResourceMine.roleID
     *
     * @param roleid the value for PlayerResourceMine.roleID
     * @mbggenerated Wed Jan 28 10:55:47 CST 2015
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PlayerResourceMine.NpcResMineID
     *
     * @return the value of PlayerResourceMine.NpcResMineID
     * @mbggenerated Wed Jan 28 10:55:47 CST 2015
     */
    public Long getNpcresmineid() {
        return npcresmineid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PlayerResourceMine.NpcResMineID
     *
     * @param npcresmineid the value for PlayerResourceMine.NpcResMineID
     * @mbggenerated Wed Jan 28 10:55:47 CST 2015
     */
    public void setNpcresmineid(Long npcresmineid) {
        this.npcresmineid = npcresmineid;
    }
}