package com.pkuvr.game_server.domain;

public class PlayermineleftresourceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PlayerMineLeftResource.roleID
     *
     * @mbggenerated Fri Jan 09 14:53:32 CST 2015
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PlayerMineLeftResource.produceResType
     *
     * @mbggenerated Fri Jan 09 14:53:32 CST 2015
     */
    private Short producerestype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PlayerMineLeftResource.roleID
     *
     * @return the value of PlayerMineLeftResource.roleID
     * @mbggenerated Fri Jan 09 14:53:32 CST 2015
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PlayerMineLeftResource.roleID
     *
     * @param roleid the value for PlayerMineLeftResource.roleID
     * @mbggenerated Fri Jan 09 14:53:32 CST 2015
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PlayerMineLeftResource.produceResType
     *
     * @return the value of PlayerMineLeftResource.produceResType
     * @mbggenerated Fri Jan 09 14:53:32 CST 2015
     */
    public Short getProducerestype() {
        return producerestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PlayerMineLeftResource.produceResType
     *
     * @param producerestype the value for PlayerMineLeftResource.produceResType
     * @mbggenerated Fri Jan 09 14:53:32 CST 2015
     */
    public void setProducerestype(Short producerestype) {
        this.producerestype = producerestype;
    }
}