package com.pkuvr.game_server.domain;

public class PlayerdefensezoneWithBLOBs extends Playerdefensezone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PlayerDefenseZone.battleUnitInfo1
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    private String battleunitinfo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PlayerDefenseZone.battleUnitInfo2
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    private String battleunitinfo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PlayerDefenseZone.battleUnitInfo3
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    private String battleunitinfo3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PlayerDefenseZone.battleUnitInfo4
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    private String battleunitinfo4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PlayerDefenseZone.battleUnitInfo1
     *
     * @return the value of PlayerDefenseZone.battleUnitInfo1
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public String getBattleunitinfo1() {
        return battleunitinfo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PlayerDefenseZone.battleUnitInfo1
     *
     * @param battleunitinfo1 the value for PlayerDefenseZone.battleUnitInfo1
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void setBattleunitinfo1(String battleunitinfo1) {
        this.battleunitinfo1 = battleunitinfo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PlayerDefenseZone.battleUnitInfo2
     *
     * @return the value of PlayerDefenseZone.battleUnitInfo2
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public String getBattleunitinfo2() {
        return battleunitinfo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PlayerDefenseZone.battleUnitInfo2
     *
     * @param battleunitinfo2 the value for PlayerDefenseZone.battleUnitInfo2
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void setBattleunitinfo2(String battleunitinfo2) {
        this.battleunitinfo2 = battleunitinfo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PlayerDefenseZone.battleUnitInfo3
     *
     * @return the value of PlayerDefenseZone.battleUnitInfo3
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public String getBattleunitinfo3() {
        return battleunitinfo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PlayerDefenseZone.battleUnitInfo3
     *
     * @param battleunitinfo3 the value for PlayerDefenseZone.battleUnitInfo3
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void setBattleunitinfo3(String battleunitinfo3) {
        this.battleunitinfo3 = battleunitinfo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PlayerDefenseZone.battleUnitInfo4
     *
     * @return the value of PlayerDefenseZone.battleUnitInfo4
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public String getBattleunitinfo4() {
        return battleunitinfo4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PlayerDefenseZone.battleUnitInfo4
     *
     * @param battleunitinfo4 the value for PlayerDefenseZone.battleUnitInfo4
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void setBattleunitinfo4(String battleunitinfo4) {
        this.battleunitinfo4 = battleunitinfo4;
    }
}