package com.pkuvr.game_server.domain;

public class RealtimepvpplayerhistoryKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column RealTimePvpPlayerHistory.roleID
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    private Integer roleid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column RealTimePvpPlayerHistory.attackeeRoleID
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    private Integer attackeeroleid;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column RealTimePvpPlayerHistory.roleID
     *
     * @return the value of RealTimePvpPlayerHistory.roleID
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column RealTimePvpPlayerHistory.roleID
     *
     * @param roleid the value for RealTimePvpPlayerHistory.roleID
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column RealTimePvpPlayerHistory.attackeeRoleID
     *
     * @return the value of RealTimePvpPlayerHistory.attackeeRoleID
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public Integer getAttackeeroleid() {
        return attackeeroleid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column RealTimePvpPlayerHistory.attackeeRoleID
     *
     * @param attackeeroleid the value for RealTimePvpPlayerHistory.attackeeRoleID
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void setAttackeeroleid(Integer attackeeroleid) {
        this.attackeeroleid = attackeeroleid;
    }
}