package com.pkuvr.game_server.domain;

public class Realtimepvptokenhistory {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column RealTimePvpTokenHistory.roleID
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    private Integer roleid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column RealTimePvpTokenHistory.tokenTimes
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    private Short tokentimes;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column RealTimePvpTokenHistory.roleID
     *
     * @return the value of RealTimePvpTokenHistory.roleID
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column RealTimePvpTokenHistory.roleID
     *
     * @param roleid the value for RealTimePvpTokenHistory.roleID
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column RealTimePvpTokenHistory.tokenTimes
     *
     * @return the value of RealTimePvpTokenHistory.tokenTimes
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public Short getTokentimes() {
        return tokentimes;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column RealTimePvpTokenHistory.tokenTimes
     *
     * @param tokentimes the value for RealTimePvpTokenHistory.tokenTimes
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void setTokentimes(Short tokentimes) {
        this.tokentimes = tokentimes;
    }
}