package com.pkuvr.game_server.domain;

public class RefreshresourcemineKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RefreshResourceMine.roleID
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RefreshResourceMine.NpcResMineID
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    private Long npcresmineid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RefreshResourceMine.roleID
     *
     * @return the value of RefreshResourceMine.roleID
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RefreshResourceMine.roleID
     *
     * @param roleid the value for RefreshResourceMine.roleID
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RefreshResourceMine.NpcResMineID
     *
     * @return the value of RefreshResourceMine.NpcResMineID
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public Long getNpcresmineid() {
        return npcresmineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RefreshResourceMine.NpcResMineID
     *
     * @param npcresmineid the value for RefreshResourceMine.NpcResMineID
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void setNpcresmineid(Long npcresmineid) {
        this.npcresmineid = npcresmineid;
    }
}