package com.pkuvr.game_server.domain;

import java.util.ArrayList;
import java.util.List;

public class ResourceminebattlelogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public ResourceminebattlelogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBattlelogidIsNull() {
            addCriterion("battleLogID is null");
            return (Criteria) this;
        }

        public Criteria andBattlelogidIsNotNull() {
            addCriterion("battleLogID is not null");
            return (Criteria) this;
        }

        public Criteria andBattlelogidEqualTo(Long value) {
            addCriterion("battleLogID =", value, "battlelogid");
            return (Criteria) this;
        }

        public Criteria andBattlelogidNotEqualTo(Long value) {
            addCriterion("battleLogID <>", value, "battlelogid");
            return (Criteria) this;
        }

        public Criteria andBattlelogidGreaterThan(Long value) {
            addCriterion("battleLogID >", value, "battlelogid");
            return (Criteria) this;
        }

        public Criteria andBattlelogidGreaterThanOrEqualTo(Long value) {
            addCriterion("battleLogID >=", value, "battlelogid");
            return (Criteria) this;
        }

        public Criteria andBattlelogidLessThan(Long value) {
            addCriterion("battleLogID <", value, "battlelogid");
            return (Criteria) this;
        }

        public Criteria andBattlelogidLessThanOrEqualTo(Long value) {
            addCriterion("battleLogID <=", value, "battlelogid");
            return (Criteria) this;
        }

        public Criteria andBattlelogidIn(List<Long> values) {
            addCriterion("battleLogID in", values, "battlelogid");
            return (Criteria) this;
        }

        public Criteria andBattlelogidNotIn(List<Long> values) {
            addCriterion("battleLogID not in", values, "battlelogid");
            return (Criteria) this;
        }

        public Criteria andBattlelogidBetween(Long value1, Long value2) {
            addCriterion("battleLogID between", value1, value2, "battlelogid");
            return (Criteria) this;
        }

        public Criteria andBattlelogidNotBetween(Long value1, Long value2) {
            addCriterion("battleLogID not between", value1, value2, "battlelogid");
            return (Criteria) this;
        }

        public Criteria andResmineinstanceidIsNull() {
            addCriterion("resMineInstanceID is null");
            return (Criteria) this;
        }

        public Criteria andResmineinstanceidIsNotNull() {
            addCriterion("resMineInstanceID is not null");
            return (Criteria) this;
        }

        public Criteria andResmineinstanceidEqualTo(Long value) {
            addCriterion("resMineInstanceID =", value, "resmineinstanceid");
            return (Criteria) this;
        }

        public Criteria andResmineinstanceidNotEqualTo(Long value) {
            addCriterion("resMineInstanceID <>", value, "resmineinstanceid");
            return (Criteria) this;
        }

        public Criteria andResmineinstanceidGreaterThan(Long value) {
            addCriterion("resMineInstanceID >", value, "resmineinstanceid");
            return (Criteria) this;
        }

        public Criteria andResmineinstanceidGreaterThanOrEqualTo(Long value) {
            addCriterion("resMineInstanceID >=", value, "resmineinstanceid");
            return (Criteria) this;
        }

        public Criteria andResmineinstanceidLessThan(Long value) {
            addCriterion("resMineInstanceID <", value, "resmineinstanceid");
            return (Criteria) this;
        }

        public Criteria andResmineinstanceidLessThanOrEqualTo(Long value) {
            addCriterion("resMineInstanceID <=", value, "resmineinstanceid");
            return (Criteria) this;
        }

        public Criteria andResmineinstanceidIn(List<Long> values) {
            addCriterion("resMineInstanceID in", values, "resmineinstanceid");
            return (Criteria) this;
        }

        public Criteria andResmineinstanceidNotIn(List<Long> values) {
            addCriterion("resMineInstanceID not in", values, "resmineinstanceid");
            return (Criteria) this;
        }

        public Criteria andResmineinstanceidBetween(Long value1, Long value2) {
            addCriterion("resMineInstanceID between", value1, value2, "resmineinstanceid");
            return (Criteria) this;
        }

        public Criteria andResmineinstanceidNotBetween(Long value1, Long value2) {
            addCriterion("resMineInstanceID not between", value1, value2, "resmineinstanceid");
            return (Criteria) this;
        }

        public Criteria andResmineidIsNull() {
            addCriterion("resMineID is null");
            return (Criteria) this;
        }

        public Criteria andResmineidIsNotNull() {
            addCriterion("resMineID is not null");
            return (Criteria) this;
        }

        public Criteria andResmineidEqualTo(Integer value) {
            addCriterion("resMineID =", value, "resmineid");
            return (Criteria) this;
        }

        public Criteria andResmineidNotEqualTo(Integer value) {
            addCriterion("resMineID <>", value, "resmineid");
            return (Criteria) this;
        }

        public Criteria andResmineidGreaterThan(Integer value) {
            addCriterion("resMineID >", value, "resmineid");
            return (Criteria) this;
        }

        public Criteria andResmineidGreaterThanOrEqualTo(Integer value) {
            addCriterion("resMineID >=", value, "resmineid");
            return (Criteria) this;
        }

        public Criteria andResmineidLessThan(Integer value) {
            addCriterion("resMineID <", value, "resmineid");
            return (Criteria) this;
        }

        public Criteria andResmineidLessThanOrEqualTo(Integer value) {
            addCriterion("resMineID <=", value, "resmineid");
            return (Criteria) this;
        }

        public Criteria andResmineidIn(List<Integer> values) {
            addCriterion("resMineID in", values, "resmineid");
            return (Criteria) this;
        }

        public Criteria andResmineidNotIn(List<Integer> values) {
            addCriterion("resMineID not in", values, "resmineid");
            return (Criteria) this;
        }

        public Criteria andResmineidBetween(Integer value1, Integer value2) {
            addCriterion("resMineID between", value1, value2, "resmineid");
            return (Criteria) this;
        }

        public Criteria andResmineidNotBetween(Integer value1, Integer value2) {
            addCriterion("resMineID not between", value1, value2, "resmineid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidIsNull() {
            addCriterion("attackerRoleID is null");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidIsNotNull() {
            addCriterion("attackerRoleID is not null");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidEqualTo(Integer value) {
            addCriterion("attackerRoleID =", value, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidNotEqualTo(Integer value) {
            addCriterion("attackerRoleID <>", value, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidGreaterThan(Integer value) {
            addCriterion("attackerRoleID >", value, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidGreaterThanOrEqualTo(Integer value) {
            addCriterion("attackerRoleID >=", value, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidLessThan(Integer value) {
            addCriterion("attackerRoleID <", value, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidLessThanOrEqualTo(Integer value) {
            addCriterion("attackerRoleID <=", value, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidIn(List<Integer> values) {
            addCriterion("attackerRoleID in", values, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidNotIn(List<Integer> values) {
            addCriterion("attackerRoleID not in", values, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidBetween(Integer value1, Integer value2) {
            addCriterion("attackerRoleID between", value1, value2, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackerroleidNotBetween(Integer value1, Integer value2) {
            addCriterion("attackerRoleID not between", value1, value2, "attackerroleid");
            return (Criteria) this;
        }

        public Criteria andAttackeeroleidIsNull() {
            addCriterion("attackeeRoleID is null");
            return (Criteria) this;
        }

        public Criteria andAttackeeroleidIsNotNull() {
            addCriterion("attackeeRoleID is not null");
            return (Criteria) this;
        }

        public Criteria andAttackeeroleidEqualTo(Integer value) {
            addCriterion("attackeeRoleID =", value, "attackeeroleid");
            return (Criteria) this;
        }

        public Criteria andAttackeeroleidNotEqualTo(Integer value) {
            addCriterion("attackeeRoleID <>", value, "attackeeroleid");
            return (Criteria) this;
        }

        public Criteria andAttackeeroleidGreaterThan(Integer value) {
            addCriterion("attackeeRoleID >", value, "attackeeroleid");
            return (Criteria) this;
        }

        public Criteria andAttackeeroleidGreaterThanOrEqualTo(Integer value) {
            addCriterion("attackeeRoleID >=", value, "attackeeroleid");
            return (Criteria) this;
        }

        public Criteria andAttackeeroleidLessThan(Integer value) {
            addCriterion("attackeeRoleID <", value, "attackeeroleid");
            return (Criteria) this;
        }

        public Criteria andAttackeeroleidLessThanOrEqualTo(Integer value) {
            addCriterion("attackeeRoleID <=", value, "attackeeroleid");
            return (Criteria) this;
        }

        public Criteria andAttackeeroleidIn(List<Integer> values) {
            addCriterion("attackeeRoleID in", values, "attackeeroleid");
            return (Criteria) this;
        }

        public Criteria andAttackeeroleidNotIn(List<Integer> values) {
            addCriterion("attackeeRoleID not in", values, "attackeeroleid");
            return (Criteria) this;
        }

        public Criteria andAttackeeroleidBetween(Integer value1, Integer value2) {
            addCriterion("attackeeRoleID between", value1, value2, "attackeeroleid");
            return (Criteria) this;
        }

        public Criteria andAttackeeroleidNotBetween(Integer value1, Integer value2) {
            addCriterion("attackeeRoleID not between", value1, value2, "attackeeroleid");
            return (Criteria) this;
        }

        public Criteria andAttackresultIsNull() {
            addCriterion("attackResult is null");
            return (Criteria) this;
        }

        public Criteria andAttackresultIsNotNull() {
            addCriterion("attackResult is not null");
            return (Criteria) this;
        }

        public Criteria andAttackresultEqualTo(Short value) {
            addCriterion("attackResult =", value, "attackresult");
            return (Criteria) this;
        }

        public Criteria andAttackresultNotEqualTo(Short value) {
            addCriterion("attackResult <>", value, "attackresult");
            return (Criteria) this;
        }

        public Criteria andAttackresultGreaterThan(Short value) {
            addCriterion("attackResult >", value, "attackresult");
            return (Criteria) this;
        }

        public Criteria andAttackresultGreaterThanOrEqualTo(Short value) {
            addCriterion("attackResult >=", value, "attackresult");
            return (Criteria) this;
        }

        public Criteria andAttackresultLessThan(Short value) {
            addCriterion("attackResult <", value, "attackresult");
            return (Criteria) this;
        }

        public Criteria andAttackresultLessThanOrEqualTo(Short value) {
            addCriterion("attackResult <=", value, "attackresult");
            return (Criteria) this;
        }

        public Criteria andAttackresultIn(List<Short> values) {
            addCriterion("attackResult in", values, "attackresult");
            return (Criteria) this;
        }

        public Criteria andAttackresultNotIn(List<Short> values) {
            addCriterion("attackResult not in", values, "attackresult");
            return (Criteria) this;
        }

        public Criteria andAttackresultBetween(Short value1, Short value2) {
            addCriterion("attackResult between", value1, value2, "attackresult");
            return (Criteria) this;
        }

        public Criteria andAttackresultNotBetween(Short value1, Short value2) {
            addCriterion("attackResult not between", value1, value2, "attackresult");
            return (Criteria) this;
        }

        public Criteria andAttacktimeIsNull() {
            addCriterion("attackTime is null");
            return (Criteria) this;
        }

        public Criteria andAttacktimeIsNotNull() {
            addCriterion("attackTime is not null");
            return (Criteria) this;
        }

        public Criteria andAttacktimeEqualTo(Long value) {
            addCriterion("attackTime =", value, "attacktime");
            return (Criteria) this;
        }

        public Criteria andAttacktimeNotEqualTo(Long value) {
            addCriterion("attackTime <>", value, "attacktime");
            return (Criteria) this;
        }

        public Criteria andAttacktimeGreaterThan(Long value) {
            addCriterion("attackTime >", value, "attacktime");
            return (Criteria) this;
        }

        public Criteria andAttacktimeGreaterThanOrEqualTo(Long value) {
            addCriterion("attackTime >=", value, "attacktime");
            return (Criteria) this;
        }

        public Criteria andAttacktimeLessThan(Long value) {
            addCriterion("attackTime <", value, "attacktime");
            return (Criteria) this;
        }

        public Criteria andAttacktimeLessThanOrEqualTo(Long value) {
            addCriterion("attackTime <=", value, "attacktime");
            return (Criteria) this;
        }

        public Criteria andAttacktimeIn(List<Long> values) {
            addCriterion("attackTime in", values, "attacktime");
            return (Criteria) this;
        }

        public Criteria andAttacktimeNotIn(List<Long> values) {
            addCriterion("attackTime not in", values, "attacktime");
            return (Criteria) this;
        }

        public Criteria andAttacktimeBetween(Long value1, Long value2) {
            addCriterion("attackTime between", value1, value2, "attacktime");
            return (Criteria) this;
        }

        public Criteria andAttacktimeNotBetween(Long value1, Long value2) {
            addCriterion("attackTime not between", value1, value2, "attacktime");
            return (Criteria) this;
        }

        public Criteria andAttackerbattleunitIsNull() {
            addCriterion("attackerBattleUnit is null");
            return (Criteria) this;
        }

        public Criteria andAttackerbattleunitIsNotNull() {
            addCriterion("attackerBattleUnit is not null");
            return (Criteria) this;
        }

        public Criteria andAttackerbattleunitEqualTo(String value) {
            addCriterion("attackerBattleUnit =", value, "attackerbattleunit");
            return (Criteria) this;
        }

        public Criteria andAttackerbattleunitNotEqualTo(String value) {
            addCriterion("attackerBattleUnit <>", value, "attackerbattleunit");
            return (Criteria) this;
        }

        public Criteria andAttackerbattleunitGreaterThan(String value) {
            addCriterion("attackerBattleUnit >", value, "attackerbattleunit");
            return (Criteria) this;
        }

        public Criteria andAttackerbattleunitGreaterThanOrEqualTo(String value) {
            addCriterion("attackerBattleUnit >=", value, "attackerbattleunit");
            return (Criteria) this;
        }

        public Criteria andAttackerbattleunitLessThan(String value) {
            addCriterion("attackerBattleUnit <", value, "attackerbattleunit");
            return (Criteria) this;
        }

        public Criteria andAttackerbattleunitLessThanOrEqualTo(String value) {
            addCriterion("attackerBattleUnit <=", value, "attackerbattleunit");
            return (Criteria) this;
        }

        public Criteria andAttackerbattleunitLike(String value) {
            addCriterion("attackerBattleUnit like", value, "attackerbattleunit");
            return (Criteria) this;
        }

        public Criteria andAttackerbattleunitNotLike(String value) {
            addCriterion("attackerBattleUnit not like", value, "attackerbattleunit");
            return (Criteria) this;
        }

        public Criteria andAttackerbattleunitIn(List<String> values) {
            addCriterion("attackerBattleUnit in", values, "attackerbattleunit");
            return (Criteria) this;
        }

        public Criteria andAttackerbattleunitNotIn(List<String> values) {
            addCriterion("attackerBattleUnit not in", values, "attackerbattleunit");
            return (Criteria) this;
        }

        public Criteria andAttackerbattleunitBetween(String value1, String value2) {
            addCriterion("attackerBattleUnit between", value1, value2, "attackerbattleunit");
            return (Criteria) this;
        }

        public Criteria andAttackerbattleunitNotBetween(String value1, String value2) {
            addCriterion("attackerBattleUnit not between", value1, value2, "attackerbattleunit");
            return (Criteria) this;
        }

        public Criteria andDamagebattleunitIsNull() {
            addCriterion("damageBattleUnit is null");
            return (Criteria) this;
        }

        public Criteria andDamagebattleunitIsNotNull() {
            addCriterion("damageBattleUnit is not null");
            return (Criteria) this;
        }

        public Criteria andDamagebattleunitEqualTo(String value) {
            addCriterion("damageBattleUnit =", value, "damagebattleunit");
            return (Criteria) this;
        }

        public Criteria andDamagebattleunitNotEqualTo(String value) {
            addCriterion("damageBattleUnit <>", value, "damagebattleunit");
            return (Criteria) this;
        }

        public Criteria andDamagebattleunitGreaterThan(String value) {
            addCriterion("damageBattleUnit >", value, "damagebattleunit");
            return (Criteria) this;
        }

        public Criteria andDamagebattleunitGreaterThanOrEqualTo(String value) {
            addCriterion("damageBattleUnit >=", value, "damagebattleunit");
            return (Criteria) this;
        }

        public Criteria andDamagebattleunitLessThan(String value) {
            addCriterion("damageBattleUnit <", value, "damagebattleunit");
            return (Criteria) this;
        }

        public Criteria andDamagebattleunitLessThanOrEqualTo(String value) {
            addCriterion("damageBattleUnit <=", value, "damagebattleunit");
            return (Criteria) this;
        }

        public Criteria andDamagebattleunitLike(String value) {
            addCriterion("damageBattleUnit like", value, "damagebattleunit");
            return (Criteria) this;
        }

        public Criteria andDamagebattleunitNotLike(String value) {
            addCriterion("damageBattleUnit not like", value, "damagebattleunit");
            return (Criteria) this;
        }

        public Criteria andDamagebattleunitIn(List<String> values) {
            addCriterion("damageBattleUnit in", values, "damagebattleunit");
            return (Criteria) this;
        }

        public Criteria andDamagebattleunitNotIn(List<String> values) {
            addCriterion("damageBattleUnit not in", values, "damagebattleunit");
            return (Criteria) this;
        }

        public Criteria andDamagebattleunitBetween(String value1, String value2) {
            addCriterion("damageBattleUnit between", value1, value2, "damagebattleunit");
            return (Criteria) this;
        }

        public Criteria andDamagebattleunitNotBetween(String value1, String value2) {
            addCriterion("damageBattleUnit not between", value1, value2, "damagebattleunit");
            return (Criteria) this;
        }

        public Criteria andAttackerrolenameIsNull() {
            addCriterion("attackerRoleName is null");
            return (Criteria) this;
        }

        public Criteria andAttackerrolenameIsNotNull() {
            addCriterion("attackerRoleName is not null");
            return (Criteria) this;
        }

        public Criteria andAttackerrolenameEqualTo(String value) {
            addCriterion("attackerRoleName =", value, "attackerrolename");
            return (Criteria) this;
        }

        public Criteria andAttackerrolenameNotEqualTo(String value) {
            addCriterion("attackerRoleName <>", value, "attackerrolename");
            return (Criteria) this;
        }

        public Criteria andAttackerrolenameGreaterThan(String value) {
            addCriterion("attackerRoleName >", value, "attackerrolename");
            return (Criteria) this;
        }

        public Criteria andAttackerrolenameGreaterThanOrEqualTo(String value) {
            addCriterion("attackerRoleName >=", value, "attackerrolename");
            return (Criteria) this;
        }

        public Criteria andAttackerrolenameLessThan(String value) {
            addCriterion("attackerRoleName <", value, "attackerrolename");
            return (Criteria) this;
        }

        public Criteria andAttackerrolenameLessThanOrEqualTo(String value) {
            addCriterion("attackerRoleName <=", value, "attackerrolename");
            return (Criteria) this;
        }

        public Criteria andAttackerrolenameLike(String value) {
            addCriterion("attackerRoleName like", value, "attackerrolename");
            return (Criteria) this;
        }

        public Criteria andAttackerrolenameNotLike(String value) {
            addCriterion("attackerRoleName not like", value, "attackerrolename");
            return (Criteria) this;
        }

        public Criteria andAttackerrolenameIn(List<String> values) {
            addCriterion("attackerRoleName in", values, "attackerrolename");
            return (Criteria) this;
        }

        public Criteria andAttackerrolenameNotIn(List<String> values) {
            addCriterion("attackerRoleName not in", values, "attackerrolename");
            return (Criteria) this;
        }

        public Criteria andAttackerrolenameBetween(String value1, String value2) {
            addCriterion("attackerRoleName between", value1, value2, "attackerrolename");
            return (Criteria) this;
        }

        public Criteria andAttackerrolenameNotBetween(String value1, String value2) {
            addCriterion("attackerRoleName not between", value1, value2, "attackerrolename");
            return (Criteria) this;
        }

        public Criteria andAttackercampidIsNull() {
            addCriterion("attackerCampId is null");
            return (Criteria) this;
        }

        public Criteria andAttackercampidIsNotNull() {
            addCriterion("attackerCampId is not null");
            return (Criteria) this;
        }

        public Criteria andAttackercampidEqualTo(Short value) {
            addCriterion("attackerCampId =", value, "attackercampid");
            return (Criteria) this;
        }

        public Criteria andAttackercampidNotEqualTo(Short value) {
            addCriterion("attackerCampId <>", value, "attackercampid");
            return (Criteria) this;
        }

        public Criteria andAttackercampidGreaterThan(Short value) {
            addCriterion("attackerCampId >", value, "attackercampid");
            return (Criteria) this;
        }

        public Criteria andAttackercampidGreaterThanOrEqualTo(Short value) {
            addCriterion("attackerCampId >=", value, "attackercampid");
            return (Criteria) this;
        }

        public Criteria andAttackercampidLessThan(Short value) {
            addCriterion("attackerCampId <", value, "attackercampid");
            return (Criteria) this;
        }

        public Criteria andAttackercampidLessThanOrEqualTo(Short value) {
            addCriterion("attackerCampId <=", value, "attackercampid");
            return (Criteria) this;
        }

        public Criteria andAttackercampidIn(List<Short> values) {
            addCriterion("attackerCampId in", values, "attackercampid");
            return (Criteria) this;
        }

        public Criteria andAttackercampidNotIn(List<Short> values) {
            addCriterion("attackerCampId not in", values, "attackercampid");
            return (Criteria) this;
        }

        public Criteria andAttackercampidBetween(Short value1, Short value2) {
            addCriterion("attackerCampId between", value1, value2, "attackercampid");
            return (Criteria) this;
        }

        public Criteria andAttackercampidNotBetween(Short value1, Short value2) {
            addCriterion("attackerCampId not between", value1, value2, "attackercampid");
            return (Criteria) this;
        }

        public Criteria andAttackeravatarIsNull() {
            addCriterion("attackerAvatar is null");
            return (Criteria) this;
        }

        public Criteria andAttackeravatarIsNotNull() {
            addCriterion("attackerAvatar is not null");
            return (Criteria) this;
        }

        public Criteria andAttackeravatarEqualTo(String value) {
            addCriterion("attackerAvatar =", value, "attackeravatar");
            return (Criteria) this;
        }

        public Criteria andAttackeravatarNotEqualTo(String value) {
            addCriterion("attackerAvatar <>", value, "attackeravatar");
            return (Criteria) this;
        }

        public Criteria andAttackeravatarGreaterThan(String value) {
            addCriterion("attackerAvatar >", value, "attackeravatar");
            return (Criteria) this;
        }

        public Criteria andAttackeravatarGreaterThanOrEqualTo(String value) {
            addCriterion("attackerAvatar >=", value, "attackeravatar");
            return (Criteria) this;
        }

        public Criteria andAttackeravatarLessThan(String value) {
            addCriterion("attackerAvatar <", value, "attackeravatar");
            return (Criteria) this;
        }

        public Criteria andAttackeravatarLessThanOrEqualTo(String value) {
            addCriterion("attackerAvatar <=", value, "attackeravatar");
            return (Criteria) this;
        }

        public Criteria andAttackeravatarLike(String value) {
            addCriterion("attackerAvatar like", value, "attackeravatar");
            return (Criteria) this;
        }

        public Criteria andAttackeravatarNotLike(String value) {
            addCriterion("attackerAvatar not like", value, "attackeravatar");
            return (Criteria) this;
        }

        public Criteria andAttackeravatarIn(List<String> values) {
            addCriterion("attackerAvatar in", values, "attackeravatar");
            return (Criteria) this;
        }

        public Criteria andAttackeravatarNotIn(List<String> values) {
            addCriterion("attackerAvatar not in", values, "attackeravatar");
            return (Criteria) this;
        }

        public Criteria andAttackeravatarBetween(String value1, String value2) {
            addCriterion("attackerAvatar between", value1, value2, "attackeravatar");
            return (Criteria) this;
        }

        public Criteria andAttackeravatarNotBetween(String value1, String value2) {
            addCriterion("attackerAvatar not between", value1, value2, "attackeravatar");
            return (Criteria) this;
        }

        public Criteria andAttackergeneraldegreeIsNull() {
            addCriterion("attackerGeneralDegree is null");
            return (Criteria) this;
        }

        public Criteria andAttackergeneraldegreeIsNotNull() {
            addCriterion("attackerGeneralDegree is not null");
            return (Criteria) this;
        }

        public Criteria andAttackergeneraldegreeEqualTo(Integer value) {
            addCriterion("attackerGeneralDegree =", value, "attackergeneraldegree");
            return (Criteria) this;
        }

        public Criteria andAttackergeneraldegreeNotEqualTo(Integer value) {
            addCriterion("attackerGeneralDegree <>", value, "attackergeneraldegree");
            return (Criteria) this;
        }

        public Criteria andAttackergeneraldegreeGreaterThan(Integer value) {
            addCriterion("attackerGeneralDegree >", value, "attackergeneraldegree");
            return (Criteria) this;
        }

        public Criteria andAttackergeneraldegreeGreaterThanOrEqualTo(Integer value) {
            addCriterion("attackerGeneralDegree >=", value, "attackergeneraldegree");
            return (Criteria) this;
        }

        public Criteria andAttackergeneraldegreeLessThan(Integer value) {
            addCriterion("attackerGeneralDegree <", value, "attackergeneraldegree");
            return (Criteria) this;
        }

        public Criteria andAttackergeneraldegreeLessThanOrEqualTo(Integer value) {
            addCriterion("attackerGeneralDegree <=", value, "attackergeneraldegree");
            return (Criteria) this;
        }

        public Criteria andAttackergeneraldegreeIn(List<Integer> values) {
            addCriterion("attackerGeneralDegree in", values, "attackergeneraldegree");
            return (Criteria) this;
        }

        public Criteria andAttackergeneraldegreeNotIn(List<Integer> values) {
            addCriterion("attackerGeneralDegree not in", values, "attackergeneraldegree");
            return (Criteria) this;
        }

        public Criteria andAttackergeneraldegreeBetween(Integer value1, Integer value2) {
            addCriterion("attackerGeneralDegree between", value1, value2, "attackergeneraldegree");
            return (Criteria) this;
        }

        public Criteria andAttackergeneraldegreeNotBetween(Integer value1, Integer value2) {
            addCriterion("attackerGeneralDegree not between", value1, value2, "attackergeneraldegree");
            return (Criteria) this;
        }

        public Criteria andAttackerrolehonorIsNull() {
            addCriterion("attackerRoleHonor is null");
            return (Criteria) this;
        }

        public Criteria andAttackerrolehonorIsNotNull() {
            addCriterion("attackerRoleHonor is not null");
            return (Criteria) this;
        }

        public Criteria andAttackerrolehonorEqualTo(Integer value) {
            addCriterion("attackerRoleHonor =", value, "attackerrolehonor");
            return (Criteria) this;
        }

        public Criteria andAttackerrolehonorNotEqualTo(Integer value) {
            addCriterion("attackerRoleHonor <>", value, "attackerrolehonor");
            return (Criteria) this;
        }

        public Criteria andAttackerrolehonorGreaterThan(Integer value) {
            addCriterion("attackerRoleHonor >", value, "attackerrolehonor");
            return (Criteria) this;
        }

        public Criteria andAttackerrolehonorGreaterThanOrEqualTo(Integer value) {
            addCriterion("attackerRoleHonor >=", value, "attackerrolehonor");
            return (Criteria) this;
        }

        public Criteria andAttackerrolehonorLessThan(Integer value) {
            addCriterion("attackerRoleHonor <", value, "attackerrolehonor");
            return (Criteria) this;
        }

        public Criteria andAttackerrolehonorLessThanOrEqualTo(Integer value) {
            addCriterion("attackerRoleHonor <=", value, "attackerrolehonor");
            return (Criteria) this;
        }

        public Criteria andAttackerrolehonorIn(List<Integer> values) {
            addCriterion("attackerRoleHonor in", values, "attackerrolehonor");
            return (Criteria) this;
        }

        public Criteria andAttackerrolehonorNotIn(List<Integer> values) {
            addCriterion("attackerRoleHonor not in", values, "attackerrolehonor");
            return (Criteria) this;
        }

        public Criteria andAttackerrolehonorBetween(Integer value1, Integer value2) {
            addCriterion("attackerRoleHonor between", value1, value2, "attackerrolehonor");
            return (Criteria) this;
        }

        public Criteria andAttackerrolehonorNotBetween(Integer value1, Integer value2) {
            addCriterion("attackerRoleHonor not between", value1, value2, "attackerrolehonor");
            return (Criteria) this;
        }

        public Criteria andRewardhonorIsNull() {
            addCriterion("rewardHonor is null");
            return (Criteria) this;
        }

        public Criteria andRewardhonorIsNotNull() {
            addCriterion("rewardHonor is not null");
            return (Criteria) this;
        }

        public Criteria andRewardhonorEqualTo(Integer value) {
            addCriterion("rewardHonor =", value, "rewardhonor");
            return (Criteria) this;
        }

        public Criteria andRewardhonorNotEqualTo(Integer value) {
            addCriterion("rewardHonor <>", value, "rewardhonor");
            return (Criteria) this;
        }

        public Criteria andRewardhonorGreaterThan(Integer value) {
            addCriterion("rewardHonor >", value, "rewardhonor");
            return (Criteria) this;
        }

        public Criteria andRewardhonorGreaterThanOrEqualTo(Integer value) {
            addCriterion("rewardHonor >=", value, "rewardhonor");
            return (Criteria) this;
        }

        public Criteria andRewardhonorLessThan(Integer value) {
            addCriterion("rewardHonor <", value, "rewardhonor");
            return (Criteria) this;
        }

        public Criteria andRewardhonorLessThanOrEqualTo(Integer value) {
            addCriterion("rewardHonor <=", value, "rewardhonor");
            return (Criteria) this;
        }

        public Criteria andRewardhonorIn(List<Integer> values) {
            addCriterion("rewardHonor in", values, "rewardhonor");
            return (Criteria) this;
        }

        public Criteria andRewardhonorNotIn(List<Integer> values) {
            addCriterion("rewardHonor not in", values, "rewardhonor");
            return (Criteria) this;
        }

        public Criteria andRewardhonorBetween(Integer value1, Integer value2) {
            addCriterion("rewardHonor between", value1, value2, "rewardhonor");
            return (Criteria) this;
        }

        public Criteria andRewardhonorNotBetween(Integer value1, Integer value2) {
            addCriterion("rewardHonor not between", value1, value2, "rewardhonor");
            return (Criteria) this;
        }

        public Criteria andProducerestypeIsNull() {
            addCriterion("produceResType is null");
            return (Criteria) this;
        }

        public Criteria andProducerestypeIsNotNull() {
            addCriterion("produceResType is not null");
            return (Criteria) this;
        }

        public Criteria andProducerestypeEqualTo(Short value) {
            addCriterion("produceResType =", value, "producerestype");
            return (Criteria) this;
        }

        public Criteria andProducerestypeNotEqualTo(Short value) {
            addCriterion("produceResType <>", value, "producerestype");
            return (Criteria) this;
        }

        public Criteria andProducerestypeGreaterThan(Short value) {
            addCriterion("produceResType >", value, "producerestype");
            return (Criteria) this;
        }

        public Criteria andProducerestypeGreaterThanOrEqualTo(Short value) {
            addCriterion("produceResType >=", value, "producerestype");
            return (Criteria) this;
        }

        public Criteria andProducerestypeLessThan(Short value) {
            addCriterion("produceResType <", value, "producerestype");
            return (Criteria) this;
        }

        public Criteria andProducerestypeLessThanOrEqualTo(Short value) {
            addCriterion("produceResType <=", value, "producerestype");
            return (Criteria) this;
        }

        public Criteria andProducerestypeIn(List<Short> values) {
            addCriterion("produceResType in", values, "producerestype");
            return (Criteria) this;
        }

        public Criteria andProducerestypeNotIn(List<Short> values) {
            addCriterion("produceResType not in", values, "producerestype");
            return (Criteria) this;
        }

        public Criteria andProducerestypeBetween(Short value1, Short value2) {
            addCriterion("produceResType between", value1, value2, "producerestype");
            return (Criteria) this;
        }

        public Criteria andProducerestypeNotBetween(Short value1, Short value2) {
            addCriterion("produceResType not between", value1, value2, "producerestype");
            return (Criteria) this;
        }

        public Criteria andRewardresourceIsNull() {
            addCriterion("rewardResource is null");
            return (Criteria) this;
        }

        public Criteria andRewardresourceIsNotNull() {
            addCriterion("rewardResource is not null");
            return (Criteria) this;
        }

        public Criteria andRewardresourceEqualTo(Integer value) {
            addCriterion("rewardResource =", value, "rewardresource");
            return (Criteria) this;
        }

        public Criteria andRewardresourceNotEqualTo(Integer value) {
            addCriterion("rewardResource <>", value, "rewardresource");
            return (Criteria) this;
        }

        public Criteria andRewardresourceGreaterThan(Integer value) {
            addCriterion("rewardResource >", value, "rewardresource");
            return (Criteria) this;
        }

        public Criteria andRewardresourceGreaterThanOrEqualTo(Integer value) {
            addCriterion("rewardResource >=", value, "rewardresource");
            return (Criteria) this;
        }

        public Criteria andRewardresourceLessThan(Integer value) {
            addCriterion("rewardResource <", value, "rewardresource");
            return (Criteria) this;
        }

        public Criteria andRewardresourceLessThanOrEqualTo(Integer value) {
            addCriterion("rewardResource <=", value, "rewardresource");
            return (Criteria) this;
        }

        public Criteria andRewardresourceIn(List<Integer> values) {
            addCriterion("rewardResource in", values, "rewardresource");
            return (Criteria) this;
        }

        public Criteria andRewardresourceNotIn(List<Integer> values) {
            addCriterion("rewardResource not in", values, "rewardresource");
            return (Criteria) this;
        }

        public Criteria andRewardresourceBetween(Integer value1, Integer value2) {
            addCriterion("rewardResource between", value1, value2, "rewardresource");
            return (Criteria) this;
        }

        public Criteria andRewardresourceNotBetween(Integer value1, Integer value2) {
            addCriterion("rewardResource not between", value1, value2, "rewardresource");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated do_not_delete_during_merge Thu May 19 12:37:02 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ResourceMineBattleLog
     *
     * @mbggenerated Thu May 19 12:37:02 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}